// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ai.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiUsageRequirement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UsageName        string                 `protobuf:"bytes,1,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"`
	RequiredCapacity int32                  `protobuf:"varint,2,opt,name=required_capacity,json=requiredCapacity,proto3" json:"required_capacity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiUsageRequirement) Reset() {
	*x = AiUsageRequirement{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiUsageRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiUsageRequirement) ProtoMessage() {}

func (x *AiUsageRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiUsageRequirement.ProtoReflect.Descriptor instead.
func (*AiUsageRequirement) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AiUsageRequirement) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *AiUsageRequirement) GetRequiredCapacity() int32 {
	if x != nil {
		return x.RequiredCapacity
	}
	return 0
}

type AiListLocationsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId   string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	AllowedLocations []string               `protobuf:"bytes,2,rep,name=allowed_locations,json=allowedLocations,proto3" json:"allowed_locations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiListLocationsRequest) Reset() {
	*x = AiListLocationsRequest{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListLocationsRequest) ProtoMessage() {}

func (x *AiListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListLocationsRequest.ProtoReflect.Descriptor instead.
func (*AiListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AiListLocationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AiListLocationsRequest) GetAllowedLocations() []string {
	if x != nil {
		return x.AllowedLocations
	}
	return nil
}

type AiListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiListLocationsResponse) Reset() {
	*x = AiListLocationsResponse{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListLocationsResponse) ProtoMessage() {}

func (x *AiListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListLocationsResponse.ProtoReflect.Descriptor instead.
func (*AiListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AiListLocationsResponse) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type AiListUsagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Location       string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	NamePrefix     string                 `protobuf:"bytes,3,opt,name=name_prefix,json=namePrefix,proto3" json:"name_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AiListUsagesRequest) Reset() {
	*x = AiListUsagesRequest{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListUsagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListUsagesRequest) ProtoMessage() {}

func (x *AiListUsagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListUsagesRequest.ProtoReflect.Descriptor instead.
func (*AiListUsagesRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AiListUsagesRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AiListUsagesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AiListUsagesRequest) GetNamePrefix() string {
	if x != nil {
		return x.NamePrefix
	}
	return ""
}

type AiUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Current       float64                `protobuf:"fixed64,2,opt,name=current,proto3" json:"current,omitempty"`
	Limit         float64                `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Remaining     float64                `protobuf:"fixed64,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiUsage) Reset() {
	*x = AiUsage{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiUsage) ProtoMessage() {}

func (x *AiUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiUsage.ProtoReflect.Descriptor instead.
func (*AiUsage) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AiUsage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiUsage) GetCurrent() float64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *AiUsage) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AiUsage) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *AiUsage) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type AiListUsagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usages        []*AiUsage             `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiListUsagesResponse) Reset() {
	*x = AiListUsagesResponse{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListUsagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListUsagesResponse) ProtoMessage() {}

func (x *AiListUsagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListUsagesResponse.ProtoReflect.Descriptor instead.
func (*AiListUsagesResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AiListUsagesResponse) GetUsages() []*AiUsage {
	if x != nil {
		return x.Usages
	}
	return nil
}

type AiModelSku struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UsageName       string                 `protobuf:"bytes,2,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"`
	CapacityDefault int32                  `protobuf:"varint,3,opt,name=capacity_default,json=capacityDefault,proto3" json:"capacity_default,omitempty"`
	CapacityMinimum int32                  `protobuf:"varint,4,opt,name=capacity_minimum,json=capacityMinimum,proto3" json:"capacity_minimum,omitempty"`
	CapacityMaximum int32                  `protobuf:"varint,5,opt,name=capacity_maximum,json=capacityMaximum,proto3" json:"capacity_maximum,omitempty"`
	CapacityStep    int32                  `protobuf:"varint,6,opt,name=capacity_step,json=capacityStep,proto3" json:"capacity_step,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AiModelSku) Reset() {
	*x = AiModelSku{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelSku) ProtoMessage() {}

func (x *AiModelSku) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelSku.ProtoReflect.Descriptor instead.
func (*AiModelSku) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *AiModelSku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiModelSku) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *AiModelSku) GetCapacityDefault() int32 {
	if x != nil {
		return x.CapacityDefault
	}
	return 0
}

func (x *AiModelSku) GetCapacityMinimum() int32 {
	if x != nil {
		return x.CapacityMinimum
	}
	return 0
}

func (x *AiModelSku) GetCapacityMaximum() int32 {
	if x != nil {
		return x.CapacityMaximum
	}
	return 0
}

func (x *AiModelSku) GetCapacityStep() int32 {
	if x != nil {
		return x.CapacityStep
	}
	return 0
}

type AiModelVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	IsDefaultVersion bool                   `protobuf:"varint,2,opt,name=is_default_version,json=isDefaultVersion,proto3" json:"is_default_version,omitempty"`
	Kind             string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Format           string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Capabilities     []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Skus             []*AiModelSku          `protobuf:"bytes,7,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiModelVersion) Reset() {
	*x = AiModelVersion{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelVersion) ProtoMessage() {}

func (x *AiModelVersion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelVersion.ProtoReflect.Descriptor instead.
func (*AiModelVersion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *AiModelVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AiModelVersion) GetIsDefaultVersion() bool {
	if x != nil {
		return x.IsDefaultVersion
	}
	return false
}

func (x *AiModelVersion) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AiModelVersion) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AiModelVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AiModelVersion) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AiModelVersion) GetSkus() []*AiModelSku {
	if x != nil {
		return x.Skus
	}
	return nil
}

type AiModelLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Versions      []*AiModelVersion      `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelLocation) Reset() {
	*x = AiModelLocation{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelLocation) ProtoMessage() {}

func (x *AiModelLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelLocation.ProtoReflect.Descriptor instead.
func (*AiModelLocation) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *AiModelLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AiModelLocation) GetVersions() []*AiModelVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type AiModelCatalogItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Locations     []*AiModelLocation     `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelCatalogItem) Reset() {
	*x = AiModelCatalogItem{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelCatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelCatalogItem) ProtoMessage() {}

func (x *AiModelCatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelCatalogItem.ProtoReflect.Descriptor instead.
func (*AiModelCatalogItem) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *AiModelCatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiModelCatalogItem) GetLocations() []*AiModelLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type AiListModelCatalogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Locations      []string               `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	Kinds          []string               `protobuf:"bytes,3,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Formats        []string               `protobuf:"bytes,4,rep,name=formats,proto3" json:"formats,omitempty"`
	Statuses       []string               `protobuf:"bytes,5,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Capabilities   []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AiListModelCatalogRequest) Reset() {
	*x = AiListModelCatalogRequest{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListModelCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListModelCatalogRequest) ProtoMessage() {}

func (x *AiListModelCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListModelCatalogRequest.ProtoReflect.Descriptor instead.
func (*AiListModelCatalogRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *AiListModelCatalogRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AiListModelCatalogRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *AiListModelCatalogRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *AiListModelCatalogRequest) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *AiListModelCatalogRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *AiListModelCatalogRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type AiListModelCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*AiModelCatalogItem  `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiListModelCatalogResponse) Reset() {
	*x = AiListModelCatalogResponse{}
	mi := &file_ai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiListModelCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiListModelCatalogResponse) ProtoMessage() {}

func (x *AiListModelCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiListModelCatalogResponse.ProtoReflect.Descriptor instead.
func (*AiListModelCatalogResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{11}
}

func (x *AiListModelCatalogResponse) GetModels() []*AiModelCatalogItem {
	if x != nil {
		return x.Models
	}
	return nil
}

type AiLocationQuotaUsage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UsageName         string                 `protobuf:"bytes,1,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"`
	RequiredCapacity  int32                  `protobuf:"varint,2,opt,name=required_capacity,json=requiredCapacity,proto3" json:"required_capacity,omitempty"`
	AvailableCapacity float64                `protobuf:"fixed64,3,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AiLocationQuotaUsage) Reset() {
	*x = AiLocationQuotaUsage{}
	mi := &file_ai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiLocationQuotaUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiLocationQuotaUsage) ProtoMessage() {}

func (x *AiLocationQuotaUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiLocationQuotaUsage.ProtoReflect.Descriptor instead.
func (*AiLocationQuotaUsage) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{12}
}

func (x *AiLocationQuotaUsage) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *AiLocationQuotaUsage) GetRequiredCapacity() int32 {
	if x != nil {
		return x.RequiredCapacity
	}
	return 0
}

func (x *AiLocationQuotaUsage) GetAvailableCapacity() float64 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

type AiLocationQuotaResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Location      string                  `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Matched       bool                    `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Requirements  []*AiLocationQuotaUsage `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Error         string                  `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiLocationQuotaResult) Reset() {
	*x = AiLocationQuotaResult{}
	mi := &file_ai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiLocationQuotaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiLocationQuotaResult) ProtoMessage() {}

func (x *AiLocationQuotaResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiLocationQuotaResult.ProtoReflect.Descriptor instead.
func (*AiLocationQuotaResult) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{13}
}

func (x *AiLocationQuotaResult) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AiLocationQuotaResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *AiLocationQuotaResult) GetRequirements() []*AiLocationQuotaUsage {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AiLocationQuotaResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AiFindLocationsWithQuotaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Locations      []string               `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	Requirements   []*AiUsageRequirement  `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AiFindLocationsWithQuotaRequest) Reset() {
	*x = AiFindLocationsWithQuotaRequest{}
	mi := &file_ai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiFindLocationsWithQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiFindLocationsWithQuotaRequest) ProtoMessage() {}

func (x *AiFindLocationsWithQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiFindLocationsWithQuotaRequest.ProtoReflect.Descriptor instead.
func (*AiFindLocationsWithQuotaRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{14}
}

func (x *AiFindLocationsWithQuotaRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AiFindLocationsWithQuotaRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *AiFindLocationsWithQuotaRequest) GetRequirements() []*AiUsageRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type AiFindLocationsWithQuotaResponse struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	MatchedLocations []string                 `protobuf:"bytes,1,rep,name=matched_locations,json=matchedLocations,proto3" json:"matched_locations,omitempty"`
	Results          []*AiLocationQuotaResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiFindLocationsWithQuotaResponse) Reset() {
	*x = AiFindLocationsWithQuotaResponse{}
	mi := &file_ai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiFindLocationsWithQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiFindLocationsWithQuotaResponse) ProtoMessage() {}

func (x *AiFindLocationsWithQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiFindLocationsWithQuotaResponse.ProtoReflect.Descriptor instead.
func (*AiFindLocationsWithQuotaResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{15}
}

func (x *AiFindLocationsWithQuotaResponse) GetMatchedLocations() []string {
	if x != nil {
		return x.MatchedLocations
	}
	return nil
}

func (x *AiFindLocationsWithQuotaResponse) GetResults() []*AiLocationQuotaResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AiModelDeployment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelName        string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	IsDefaultVersion bool                   `protobuf:"varint,3,opt,name=is_default_version,json=isDefaultVersion,proto3" json:"is_default_version,omitempty"`
	Kind             string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Format           string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Capabilities     []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Sku              *AiModelSku            `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiModelDeployment) Reset() {
	*x = AiModelDeployment{}
	mi := &file_ai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelDeployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelDeployment) ProtoMessage() {}

func (x *AiModelDeployment) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelDeployment.ProtoReflect.Descriptor instead.
func (*AiModelDeployment) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{16}
}

func (x *AiModelDeployment) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AiModelDeployment) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AiModelDeployment) GetIsDefaultVersion() bool {
	if x != nil {
		return x.IsDefaultVersion
	}
	return false
}

func (x *AiModelDeployment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AiModelDeployment) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AiModelDeployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AiModelDeployment) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AiModelDeployment) GetSku() *AiModelSku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type AiModelLocationQuotaResult struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Location      string                  `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Matched       bool                    `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Deployment    *AiModelDeployment      `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	Requirements  []*AiLocationQuotaUsage `protobuf:"bytes,4,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Error         string                  `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelLocationQuotaResult) Reset() {
	*x = AiModelLocationQuotaResult{}
	mi := &file_ai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelLocationQuotaResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelLocationQuotaResult) ProtoMessage() {}

func (x *AiModelLocationQuotaResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelLocationQuotaResult.ProtoReflect.Descriptor instead.
func (*AiModelLocationQuotaResult) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{17}
}

func (x *AiModelLocationQuotaResult) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AiModelLocationQuotaResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *AiModelLocationQuotaResult) GetDeployment() *AiModelDeployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *AiModelLocationQuotaResult) GetRequirements() []*AiLocationQuotaUsage {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AiModelLocationQuotaResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AiFindLocationsForModelWithQuotaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Locations      []string               `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	Versions       []string               `protobuf:"bytes,4,rep,name=versions,proto3" json:"versions,omitempty"`
	Skus           []string               `protobuf:"bytes,5,rep,name=skus,proto3" json:"skus,omitempty"`
	Kinds          []string               `protobuf:"bytes,6,rep,name=kinds,proto3" json:"kinds,omitempty"`
	Formats        []string               `protobuf:"bytes,7,rep,name=formats,proto3" json:"formats,omitempty"`
	Statuses       []string               `protobuf:"bytes,8,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Capabilities   []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Requirements   []*AiUsageRequirement  `protobuf:"bytes,10,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AiFindLocationsForModelWithQuotaRequest) Reset() {
	*x = AiFindLocationsForModelWithQuotaRequest{}
	mi := &file_ai_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiFindLocationsForModelWithQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiFindLocationsForModelWithQuotaRequest) ProtoMessage() {}

func (x *AiFindLocationsForModelWithQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiFindLocationsForModelWithQuotaRequest.ProtoReflect.Descriptor instead.
func (*AiFindLocationsForModelWithQuotaRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{18}
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaRequest) GetRequirements() []*AiUsageRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type AiFindLocationsForModelWithQuotaResponse struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	MatchedLocations []string                      `protobuf:"bytes,1,rep,name=matched_locations,json=matchedLocations,proto3" json:"matched_locations,omitempty"`
	Results          []*AiModelLocationQuotaResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiFindLocationsForModelWithQuotaResponse) Reset() {
	*x = AiFindLocationsForModelWithQuotaResponse{}
	mi := &file_ai_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiFindLocationsForModelWithQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiFindLocationsForModelWithQuotaResponse) ProtoMessage() {}

func (x *AiFindLocationsForModelWithQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiFindLocationsForModelWithQuotaResponse.ProtoReflect.Descriptor instead.
func (*AiFindLocationsForModelWithQuotaResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{19}
}

func (x *AiFindLocationsForModelWithQuotaResponse) GetMatchedLocations() []string {
	if x != nil {
		return x.MatchedLocations
	}
	return nil
}

func (x *AiFindLocationsForModelWithQuotaResponse) GetResults() []*AiModelLocationQuotaResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x06azdext\"`\n" +
	"\x12AiUsageRequirement\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x01 \x01(\tR\tusageName\x12+\n" +
	"\x11required_capacity\x18\x02 \x01(\x05R\x10requiredCapacity\"n\n" +
	"\x16AiListLocationsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12+\n" +
	"\x11allowed_locations\x18\x02 \x03(\tR\x10allowedLocations\"7\n" +
	"\x17AiListLocationsResponse\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\"{\n" +
	"\x13AiListUsagesRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1f\n" +
	"\vname_prefix\x18\x03 \x01(\tR\n" +
	"namePrefix\"\x7f\n" +
	"\aAiUsage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x01R\acurrent\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x01R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x01R\tremaining\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\"?\n" +
	"\x14AiListUsagesResponse\x12'\n" +
	"\x06usages\x18\x01 \x03(\v2\x0f.azdext.AiUsageR\x06usages\"\xe5\x01\n" +
	"\n" +
	"AiModelSku\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x02 \x01(\tR\tusageName\x12)\n" +
	"\x10capacity_default\x18\x03 \x01(\x05R\x0fcapacityDefault\x12)\n" +
	"\x10capacity_minimum\x18\x04 \x01(\x05R\x0fcapacityMinimum\x12)\n" +
	"\x10capacity_maximum\x18\x05 \x01(\x05R\x0fcapacityMaximum\x12#\n" +
	"\rcapacity_step\x18\x06 \x01(\x05R\fcapacityStep\"\xe8\x01\n" +
	"\x0eAiModelVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12,\n" +
	"\x12is_default_version\x18\x02 \x01(\bR\x10isDefaultVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12&\n" +
	"\x04skus\x18\a \x03(\v2\x12.azdext.AiModelSkuR\x04skus\"a\n" +
	"\x0fAiModelLocation\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x122\n" +
	"\bversions\x18\x02 \x03(\v2\x16.azdext.AiModelVersionR\bversions\"_\n" +
	"\x12AiModelCatalogItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\tlocations\x18\x02 \x03(\v2\x17.azdext.AiModelLocationR\tlocations\"\xd2\x01\n" +
	"\x19AiListModelCatalogRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\tlocations\x18\x02 \x03(\tR\tlocations\x12\x14\n" +
	"\x05kinds\x18\x03 \x03(\tR\x05kinds\x12\x18\n" +
	"\aformats\x18\x04 \x03(\tR\aformats\x12\x1a\n" +
	"\bstatuses\x18\x05 \x03(\tR\bstatuses\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\"P\n" +
	"\x1aAiListModelCatalogResponse\x122\n" +
	"\x06models\x18\x01 \x03(\v2\x1a.azdext.AiModelCatalogItemR\x06models\"\x91\x01\n" +
	"\x14AiLocationQuotaUsage\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x01 \x01(\tR\tusageName\x12+\n" +
	"\x11required_capacity\x18\x02 \x01(\x05R\x10requiredCapacity\x12-\n" +
	"\x12available_capacity\x18\x03 \x01(\x01R\x11availableCapacity\"\xa5\x01\n" +
	"\x15AiLocationQuotaResult\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12@\n" +
	"\frequirements\x18\x03 \x03(\v2\x1c.azdext.AiLocationQuotaUsageR\frequirements\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xa8\x01\n" +
	"\x1fAiFindLocationsWithQuotaRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\tlocations\x18\x02 \x03(\tR\tlocations\x12>\n" +
	"\frequirements\x18\x03 \x03(\v2\x1a.azdext.AiUsageRequirementR\frequirements\"\x88\x01\n" +
	" AiFindLocationsWithQuotaResponse\x12+\n" +
	"\x11matched_locations\x18\x01 \x03(\tR\x10matchedLocations\x127\n" +
	"\aresults\x18\x02 \x03(\v2\x1d.azdext.AiLocationQuotaResultR\aresults\"\x88\x02\n" +
	"\x11AiModelDeployment\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12,\n" +
	"\x12is_default_version\x18\x03 \x01(\bR\x10isDefaultVersion\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x12$\n" +
	"\x03sku\x18\b \x01(\v2\x12.azdext.AiModelSkuR\x03sku\"\xe5\x01\n" +
	"\x1aAiModelLocationQuotaResult\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x129\n" +
	"\n" +
	"deployment\x18\x03 \x01(\v2\x19.azdext.AiModelDeploymentR\n" +
	"deployment\x12@\n" +
	"\frequirements\x18\x04 \x03(\v2\x1c.azdext.AiLocationQuotaUsageR\frequirements\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xef\x02\n" +
	"'AiFindLocationsForModelWithQuotaRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tlocations\x18\x03 \x03(\tR\tlocations\x12\x1a\n" +
	"\bversions\x18\x04 \x03(\tR\bversions\x12\x12\n" +
	"\x04skus\x18\x05 \x03(\tR\x04skus\x12\x14\n" +
	"\x05kinds\x18\x06 \x03(\tR\x05kinds\x12\x18\n" +
	"\aformats\x18\a \x03(\tR\aformats\x12\x1a\n" +
	"\bstatuses\x18\b \x03(\tR\bstatuses\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\x12>\n" +
	"\frequirements\x18\n" +
	" \x03(\v2\x1a.azdext.AiUsageRequirementR\frequirements\"\x95\x01\n" +
	"(AiFindLocationsForModelWithQuotaResponse\x12+\n" +
	"\x11matched_locations\x18\x01 \x03(\tR\x10matchedLocations\x12<\n" +
	"\aresults\x18\x02 \x03(\v2\".azdext.AiModelLocationQuotaResultR\aresults2\xf4\x03\n" +
	"\tAiService\x12P\n" +
	"\rListLocations\x12\x1e.azdext.AiListLocationsRequest\x1a\x1f.azdext.AiListLocationsResponse\x12Y\n" +
	"\x10ListModelCatalog\x12!.azdext.AiListModelCatalogRequest\x1a\".azdext.AiListModelCatalogResponse\x12G\n" +
	"\n" +
	"ListUsages\x12\x1b.azdext.AiListUsagesRequest\x1a\x1c.azdext.AiListUsagesResponse\x12k\n" +
	"\x16FindLocationsWithQuota\x12'.azdext.AiFindLocationsWithQuotaRequest\x1a(.azdext.AiFindLocationsWithQuotaResponse\x12\x83\x01\n" +
	"\x1eFindLocationsForModelWithQuota\x12/.azdext.AiFindLocationsForModelWithQuotaRequest\x1a0.azdext.AiFindLocationsForModelWithQuotaResponseB/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_ai_proto_goTypes = []any{
	(*AiUsageRequirement)(nil),                       // 0: azdext.AiUsageRequirement
	(*AiListLocationsRequest)(nil),                   // 1: azdext.AiListLocationsRequest
	(*AiListLocationsResponse)(nil),                  // 2: azdext.AiListLocationsResponse
	(*AiListUsagesRequest)(nil),                      // 3: azdext.AiListUsagesRequest
	(*AiUsage)(nil),                                  // 4: azdext.AiUsage
	(*AiListUsagesResponse)(nil),                     // 5: azdext.AiListUsagesResponse
	(*AiModelSku)(nil),                               // 6: azdext.AiModelSku
	(*AiModelVersion)(nil),                           // 7: azdext.AiModelVersion
	(*AiModelLocation)(nil),                          // 8: azdext.AiModelLocation
	(*AiModelCatalogItem)(nil),                       // 9: azdext.AiModelCatalogItem
	(*AiListModelCatalogRequest)(nil),                // 10: azdext.AiListModelCatalogRequest
	(*AiListModelCatalogResponse)(nil),               // 11: azdext.AiListModelCatalogResponse
	(*AiLocationQuotaUsage)(nil),                     // 12: azdext.AiLocationQuotaUsage
	(*AiLocationQuotaResult)(nil),                    // 13: azdext.AiLocationQuotaResult
	(*AiFindLocationsWithQuotaRequest)(nil),          // 14: azdext.AiFindLocationsWithQuotaRequest
	(*AiFindLocationsWithQuotaResponse)(nil),         // 15: azdext.AiFindLocationsWithQuotaResponse
	(*AiModelDeployment)(nil),                        // 16: azdext.AiModelDeployment
	(*AiModelLocationQuotaResult)(nil),               // 17: azdext.AiModelLocationQuotaResult
	(*AiFindLocationsForModelWithQuotaRequest)(nil),  // 18: azdext.AiFindLocationsForModelWithQuotaRequest
	(*AiFindLocationsForModelWithQuotaResponse)(nil), // 19: azdext.AiFindLocationsForModelWithQuotaResponse
}
var file_ai_proto_depIdxs = []int32{
	4,  // 0: azdext.AiListUsagesResponse.usages:type_name -> azdext.AiUsage
	6,  // 1: azdext.AiModelVersion.skus:type_name -> azdext.AiModelSku
	7,  // 2: azdext.AiModelLocation.versions:type_name -> azdext.AiModelVersion
	8,  // 3: azdext.AiModelCatalogItem.locations:type_name -> azdext.AiModelLocation
	9,  // 4: azdext.AiListModelCatalogResponse.models:type_name -> azdext.AiModelCatalogItem
	12, // 5: azdext.AiLocationQuotaResult.requirements:type_name -> azdext.AiLocationQuotaUsage
	0,  // 6: azdext.AiFindLocationsWithQuotaRequest.requirements:type_name -> azdext.AiUsageRequirement
	13, // 7: azdext.AiFindLocationsWithQuotaResponse.results:type_name -> azdext.AiLocationQuotaResult
	6,  // 8: azdext.AiModelDeployment.sku:type_name -> azdext.AiModelSku
	16, // 9: azdext.AiModelLocationQuotaResult.deployment:type_name -> azdext.AiModelDeployment
	12, // 10: azdext.AiModelLocationQuotaResult.requirements:type_name -> azdext.AiLocationQuotaUsage
	0,  // 11: azdext.AiFindLocationsForModelWithQuotaRequest.requirements:type_name -> azdext.AiUsageRequirement
	17, // 12: azdext.AiFindLocationsForModelWithQuotaResponse.results:type_name -> azdext.AiModelLocationQuotaResult
	1,  // 13: azdext.AiService.ListLocations:input_type -> azdext.AiListLocationsRequest
	10, // 14: azdext.AiService.ListModelCatalog:input_type -> azdext.AiListModelCatalogRequest
	3,  // 15: azdext.AiService.ListUsages:input_type -> azdext.AiListUsagesRequest
	14, // 16: azdext.AiService.FindLocationsWithQuota:input_type -> azdext.AiFindLocationsWithQuotaRequest
	18, // 17: azdext.AiService.FindLocationsForModelWithQuota:input_type -> azdext.AiFindLocationsForModelWithQuotaRequest
	2,  // 18: azdext.AiService.ListLocations:output_type -> azdext.AiListLocationsResponse
	11, // 19: azdext.AiService.ListModelCatalog:output_type -> azdext.AiListModelCatalogResponse
	5,  // 20: azdext.AiService.ListUsages:output_type -> azdext.AiListUsagesResponse
	15, // 21: azdext.AiService.FindLocationsWithQuota:output_type -> azdext.AiFindLocationsWithQuotaResponse
	19, // 22: azdext.AiService.FindLocationsForModelWithQuota:output_type -> azdext.AiFindLocationsForModelWithQuotaResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
