// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: ai.proto

package azdext

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AiService_ListLocations_FullMethodName                  = "/azdext.AiService/ListLocations"
	AiService_ListModelCatalog_FullMethodName               = "/azdext.AiService/ListModelCatalog"
	AiService_ListUsages_FullMethodName                     = "/azdext.AiService/ListUsages"
	AiService_FindLocationsWithQuota_FullMethodName         = "/azdext.AiService/FindLocationsWithQuota"
	AiService_FindLocationsForModelWithQuota_FullMethodName = "/azdext.AiService/FindLocationsForModelWithQuota"
)

// AiServiceClient is the client API for AiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiServiceClient interface {
	// ListLocations lists Azure locations that support Azure AI Services accounts for the subscription.
	ListLocations(ctx context.Context, in *AiListLocationsRequest, opts ...grpc.CallOption) (*AiListLocationsResponse, error)
	// ListModelCatalog lists Azure AI models and deployment metadata available in the requested locations.
	ListModelCatalog(ctx context.Context, in *AiListModelCatalogRequest, opts ...grpc.CallOption) (*AiListModelCatalogResponse, error)
	// ListUsages lists Azure AI quota usage details for a location.
	ListUsages(ctx context.Context, in *AiListUsagesRequest, opts ...grpc.CallOption) (*AiListUsagesResponse, error)
	// FindLocationsWithQuota resolves locations that satisfy all requested quota requirements.
	FindLocationsWithQuota(ctx context.Context, in *AiFindLocationsWithQuotaRequest, opts ...grpc.CallOption) (*AiFindLocationsWithQuotaResponse, error)
	// FindLocationsForModelWithQuota resolves locations where a model deployment is available and quota requirements are met.
	FindLocationsForModelWithQuota(ctx context.Context, in *AiFindLocationsForModelWithQuotaRequest, opts ...grpc.CallOption) (*AiFindLocationsForModelWithQuotaResponse, error)
}

type aiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAiServiceClient(cc grpc.ClientConnInterface) AiServiceClient {
	return &aiServiceClient{cc}
}

func (c *aiServiceClient) ListLocations(ctx context.Context, in *AiListLocationsRequest, opts ...grpc.CallOption) (*AiListLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiListLocationsResponse)
	err := c.cc.Invoke(ctx, AiService_ListLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) ListModelCatalog(ctx context.Context, in *AiListModelCatalogRequest, opts ...grpc.CallOption) (*AiListModelCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiListModelCatalogResponse)
	err := c.cc.Invoke(ctx, AiService_ListModelCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) ListUsages(ctx context.Context, in *AiListUsagesRequest, opts ...grpc.CallOption) (*AiListUsagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiListUsagesResponse)
	err := c.cc.Invoke(ctx, AiService_ListUsages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) FindLocationsWithQuota(ctx context.Context, in *AiFindLocationsWithQuotaRequest, opts ...grpc.CallOption) (*AiFindLocationsWithQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiFindLocationsWithQuotaResponse)
	err := c.cc.Invoke(ctx, AiService_FindLocationsWithQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiServiceClient) FindLocationsForModelWithQuota(ctx context.Context, in *AiFindLocationsForModelWithQuotaRequest, opts ...grpc.CallOption) (*AiFindLocationsForModelWithQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AiFindLocationsForModelWithQuotaResponse)
	err := c.cc.Invoke(ctx, AiService_FindLocationsForModelWithQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServiceServer is the server API for AiService service.
// All implementations must embed UnimplementedAiServiceServer
// for forward compatibility.
type AiServiceServer interface {
	// ListLocations lists Azure locations that support Azure AI Services accounts for the subscription.
	ListLocations(context.Context, *AiListLocationsRequest) (*AiListLocationsResponse, error)
	// ListModelCatalog lists Azure AI models and deployment metadata available in the requested locations.
	ListModelCatalog(context.Context, *AiListModelCatalogRequest) (*AiListModelCatalogResponse, error)
	// ListUsages lists Azure AI quota usage details for a location.
	ListUsages(context.Context, *AiListUsagesRequest) (*AiListUsagesResponse, error)
	// FindLocationsWithQuota resolves locations that satisfy all requested quota requirements.
	FindLocationsWithQuota(context.Context, *AiFindLocationsWithQuotaRequest) (*AiFindLocationsWithQuotaResponse, error)
	// FindLocationsForModelWithQuota resolves locations where a model deployment is available and quota requirements are met.
	FindLocationsForModelWithQuota(context.Context, *AiFindLocationsForModelWithQuotaRequest) (*AiFindLocationsForModelWithQuotaResponse, error)
	mustEmbedUnimplementedAiServiceServer()
}

// UnimplementedAiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServiceServer struct{}

func (UnimplementedAiServiceServer) ListLocations(context.Context, *AiListLocationsRequest) (*AiListLocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLocations not implemented")
}
func (UnimplementedAiServiceServer) ListModelCatalog(context.Context, *AiListModelCatalogRequest) (*AiListModelCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModelCatalog not implemented")
}
func (UnimplementedAiServiceServer) ListUsages(context.Context, *AiListUsagesRequest) (*AiListUsagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsages not implemented")
}
func (UnimplementedAiServiceServer) FindLocationsWithQuota(context.Context, *AiFindLocationsWithQuotaRequest) (*AiFindLocationsWithQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindLocationsWithQuota not implemented")
}
func (UnimplementedAiServiceServer) FindLocationsForModelWithQuota(context.Context, *AiFindLocationsForModelWithQuotaRequest) (*AiFindLocationsForModelWithQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindLocationsForModelWithQuota not implemented")
}
func (UnimplementedAiServiceServer) mustEmbedUnimplementedAiServiceServer() {}
func (UnimplementedAiServiceServer) testEmbeddedByValue()                   {}

// UnsafeAiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServiceServer will
// result in compilation errors.
type UnsafeAiServiceServer interface {
	mustEmbedUnimplementedAiServiceServer()
}

func RegisterAiServiceServer(s grpc.ServiceRegistrar, srv AiServiceServer) {
	// If the following call panics, it indicates UnimplementedAiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AiService_ServiceDesc, srv)
}

func _AiService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ListLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ListLocations(ctx, req.(*AiListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_ListModelCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiListModelCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ListModelCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ListModelCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ListModelCatalog(ctx, req.(*AiListModelCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_ListUsages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiListUsagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).ListUsages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_ListUsages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).ListUsages(ctx, req.(*AiListUsagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_FindLocationsWithQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiFindLocationsWithQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).FindLocationsWithQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_FindLocationsWithQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).FindLocationsWithQuota(ctx, req.(*AiFindLocationsWithQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AiService_FindLocationsForModelWithQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AiFindLocationsForModelWithQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServiceServer).FindLocationsForModelWithQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AiService_FindLocationsForModelWithQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServiceServer).FindLocationsForModelWithQuota(ctx, req.(*AiFindLocationsForModelWithQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AiService_ServiceDesc is the grpc.ServiceDesc for AiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "azdext.AiService",
	HandlerType: (*AiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLocations",
			Handler:    _AiService_ListLocations_Handler,
		},
		{
			MethodName: "ListModelCatalog",
			Handler:    _AiService_ListModelCatalog_Handler,
		},
		{
			MethodName: "ListUsages",
			Handler:    _AiService_ListUsages_Handler,
		},
		{
			MethodName: "FindLocationsWithQuota",
			Handler:    _AiService_FindLocationsWithQuota_Handler,
		},
		{
			MethodName: "FindLocationsForModelWithQuota",
			Handler:    _AiService_FindLocationsForModelWithQuota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
