// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: ai_model.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AiModelFilterOptions defines filtering criteria for AI models.
type AiModelFilterOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // e.g. ["chat", "embeddings"]
	Statuses      []string               `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`         // lifecycle status filter
	Formats       []string               `protobuf:"bytes,3,rep,name=formats,proto3" json:"formats,omitempty"`           // e.g. ["OpenAI"]
	Kinds         []string               `protobuf:"bytes,4,rep,name=kinds,proto3" json:"kinds,omitempty"`               // e.g. ["OpenAI", "AIServices"]
	Locations     []string               `protobuf:"bytes,5,rep,name=locations,proto3" json:"locations,omitempty"`       // filter by specific locations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelFilterOptions) Reset() {
	*x = AiModelFilterOptions{}
	mi := &file_ai_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelFilterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelFilterOptions) ProtoMessage() {}

func (x *AiModelFilterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelFilterOptions.ProtoReflect.Descriptor instead.
func (*AiModelFilterOptions) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{0}
}

func (x *AiModelFilterOptions) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AiModelFilterOptions) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *AiModelFilterOptions) GetFormats() []string {
	if x != nil {
		return x.Formats
	}
	return nil
}

func (x *AiModelFilterOptions) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *AiModelFilterOptions) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type ListModelsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// If empty, aggregates models across all locations concurrently.
	Location      *string               `protobuf:"bytes,2,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Filter        *AiModelFilterOptions `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_ai_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{1}
}

func (x *ListModelsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListModelsRequest) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *ListModelsRequest) GetFilter() *AiModelFilterOptions {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*AiModel             `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_ai_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsResponse) GetModels() []*AiModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type AiModel struct {
	state             protoimpl.MessageState             `protogen:"open.v1"`
	Name              string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DetailsByLocation map[string]*AiModelLocationDetails `protobuf:"bytes,2,rep,name=details_by_location,json=detailsByLocation,proto3" json:"details_by_location,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AiModel) Reset() {
	*x = AiModel{}
	mi := &file_ai_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModel) ProtoMessage() {}

func (x *AiModel) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModel.ProtoReflect.Descriptor instead.
func (*AiModel) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{3}
}

func (x *AiModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiModel) GetDetailsByLocation() map[string]*AiModelLocationDetails {
	if x != nil {
		return x.DetailsByLocation
	}
	return nil
}

type AiModelLocationDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*AiModelVersion      `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelLocationDetails) Reset() {
	*x = AiModelLocationDetails{}
	mi := &file_ai_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelLocationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelLocationDetails) ProtoMessage() {}

func (x *AiModelLocationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelLocationDetails.ProtoReflect.Descriptor instead.
func (*AiModelLocationDetails) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{4}
}

func (x *AiModelLocationDetails) GetVersions() []*AiModelVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type AiModelVersion struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Format           string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Kind             string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	IsDefaultVersion bool                   `protobuf:"varint,4,opt,name=is_default_version,json=isDefaultVersion,proto3" json:"is_default_version,omitempty"`
	LifecycleStatus  string                 `protobuf:"bytes,5,opt,name=lifecycle_status,json=lifecycleStatus,proto3" json:"lifecycle_status,omitempty"`
	Capabilities     map[string]string      `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Skus             []*AiModelSku          `protobuf:"bytes,7,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AiModelVersion) Reset() {
	*x = AiModelVersion{}
	mi := &file_ai_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelVersion) ProtoMessage() {}

func (x *AiModelVersion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelVersion.ProtoReflect.Descriptor instead.
func (*AiModelVersion) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{5}
}

func (x *AiModelVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AiModelVersion) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AiModelVersion) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AiModelVersion) GetIsDefaultVersion() bool {
	if x != nil {
		return x.IsDefaultVersion
	}
	return false
}

func (x *AiModelVersion) GetLifecycleStatus() string {
	if x != nil {
		return x.LifecycleStatus
	}
	return ""
}

func (x *AiModelVersion) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AiModelVersion) GetSkus() []*AiModelSku {
	if x != nil {
		return x.Skus
	}
	return nil
}

type AiModelSku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // e.g. "Standard", "GlobalStandard"
	UsageName     string                 `protobuf:"bytes,2,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"` // e.g. "OpenAI.Standard.gpt-4o"
	Capacity      *AiModelSkuCapacity    `protobuf:"bytes,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelSku) Reset() {
	*x = AiModelSku{}
	mi := &file_ai_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelSku) ProtoMessage() {}

func (x *AiModelSku) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelSku.ProtoReflect.Descriptor instead.
func (*AiModelSku) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{6}
}

func (x *AiModelSku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiModelSku) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *AiModelSku) GetCapacity() *AiModelSkuCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type AiModelSkuCapacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefaultValue  int32                  `protobuf:"varint,1,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Maximum       int32                  `protobuf:"varint,2,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Minimum       int32                  `protobuf:"varint,3,opt,name=minimum,proto3" json:"minimum,omitempty"`
	Step          int32                  `protobuf:"varint,4,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelSkuCapacity) Reset() {
	*x = AiModelSkuCapacity{}
	mi := &file_ai_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelSkuCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelSkuCapacity) ProtoMessage() {}

func (x *AiModelSkuCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelSkuCapacity.ProtoReflect.Descriptor instead.
func (*AiModelSkuCapacity) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{7}
}

func (x *AiModelSkuCapacity) GetDefaultValue() int32 {
	if x != nil {
		return x.DefaultValue
	}
	return 0
}

func (x *AiModelSkuCapacity) GetMaximum() int32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *AiModelSkuCapacity) GetMinimum() int32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *AiModelSkuCapacity) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

type ListModelVersionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Location       string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelVersionsRequest) Reset() {
	*x = ListModelVersionsRequest{}
	mi := &file_ai_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelVersionsRequest) ProtoMessage() {}

func (x *ListModelVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListModelVersionsRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListModelVersionsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListModelVersionsRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ListModelVersionsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListModelVersionsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Versions       []string               `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	DefaultVersion string                 `protobuf:"bytes,2,opt,name=default_version,json=defaultVersion,proto3" json:"default_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelVersionsResponse) Reset() {
	*x = ListModelVersionsResponse{}
	mi := &file_ai_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelVersionsResponse) ProtoMessage() {}

func (x *ListModelVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListModelVersionsResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListModelVersionsResponse) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListModelVersionsResponse) GetDefaultVersion() string {
	if x != nil {
		return x.DefaultVersion
	}
	return ""
}

type ListModelSkusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Location       string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListModelSkusRequest) Reset() {
	*x = ListModelSkusRequest{}
	mi := &file_ai_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelSkusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelSkusRequest) ProtoMessage() {}

func (x *ListModelSkusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelSkusRequest.ProtoReflect.Descriptor instead.
func (*ListModelSkusRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{10}
}

func (x *ListModelSkusRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListModelSkusRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ListModelSkusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListModelSkusRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListModelSkusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []string               `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelSkusResponse) Reset() {
	*x = ListModelSkusResponse{}
	mi := &file_ai_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelSkusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelSkusResponse) ProtoMessage() {}

func (x *ListModelSkusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelSkusResponse.ProtoReflect.Descriptor instead.
func (*ListModelSkusResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{11}
}

func (x *ListModelSkusResponse) GetSkus() []string {
	if x != nil {
		return x.Skus
	}
	return nil
}

type GetModelDeploymentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId     string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName          string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	PreferredLocations []string               `protobuf:"bytes,3,rep,name=preferred_locations,json=preferredLocations,proto3" json:"preferred_locations,omitempty"`
	PreferredVersions  []string               `protobuf:"bytes,4,rep,name=preferred_versions,json=preferredVersions,proto3" json:"preferred_versions,omitempty"`
	// Defaults to ["GlobalStandard", "Standard"] if empty.
	PreferredSkus []string `protobuf:"bytes,5,rep,name=preferred_skus,json=preferredSkus,proto3" json:"preferred_skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelDeploymentRequest) Reset() {
	*x = GetModelDeploymentRequest{}
	mi := &file_ai_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDeploymentRequest) ProtoMessage() {}

func (x *GetModelDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDeploymentRequest.ProtoReflect.Descriptor instead.
func (*GetModelDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{12}
}

func (x *GetModelDeploymentRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetModelDeploymentRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GetModelDeploymentRequest) GetPreferredLocations() []string {
	if x != nil {
		return x.PreferredLocations
	}
	return nil
}

func (x *GetModelDeploymentRequest) GetPreferredVersions() []string {
	if x != nil {
		return x.PreferredVersions
	}
	return nil
}

func (x *GetModelDeploymentRequest) GetPreferredSkus() []string {
	if x != nil {
		return x.PreferredSkus
	}
	return nil
}

type GetModelDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Sku           *AiModelDeploymentSku  `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelDeploymentResponse) Reset() {
	*x = GetModelDeploymentResponse{}
	mi := &file_ai_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDeploymentResponse) ProtoMessage() {}

func (x *GetModelDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDeploymentResponse.ProtoReflect.Descriptor instead.
func (*GetModelDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{13}
}

func (x *GetModelDeploymentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetModelDeploymentResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GetModelDeploymentResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetModelDeploymentResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GetModelDeploymentResponse) GetSku() *AiModelDeploymentSku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type AiModelDeploymentSku struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UsageName     string                 `protobuf:"bytes,2,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiModelDeploymentSku) Reset() {
	*x = AiModelDeploymentSku{}
	mi := &file_ai_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiModelDeploymentSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiModelDeploymentSku) ProtoMessage() {}

func (x *AiModelDeploymentSku) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiModelDeploymentSku.ProtoReflect.Descriptor instead.
func (*AiModelDeploymentSku) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{14}
}

func (x *AiModelDeploymentSku) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiModelDeploymentSku) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *AiModelDeploymentSku) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type ListUsagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Location       string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListUsagesRequest) Reset() {
	*x = ListUsagesRequest{}
	mi := &file_ai_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsagesRequest) ProtoMessage() {}

func (x *ListUsagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsagesRequest.ProtoReflect.Descriptor instead.
func (*ListUsagesRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{15}
}

func (x *ListUsagesRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListUsagesRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type ListUsagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usages        []*AiUsage             `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsagesResponse) Reset() {
	*x = ListUsagesResponse{}
	mi := &file_ai_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsagesResponse) ProtoMessage() {}

func (x *ListUsagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsagesResponse.ProtoReflect.Descriptor instead.
func (*ListUsagesResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsagesResponse) GetUsages() []*AiUsage {
	if x != nil {
		return x.Usages
	}
	return nil
}

type AiUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // e.g. "OpenAI.S0.AccountCount"
	CurrentValue  float64                `protobuf:"fixed64,2,opt,name=current_value,json=currentValue,proto3" json:"current_value,omitempty"`
	Limit         float64                `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiUsage) Reset() {
	*x = AiUsage{}
	mi := &file_ai_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiUsage) ProtoMessage() {}

func (x *AiUsage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiUsage.ProtoReflect.Descriptor instead.
func (*AiUsage) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{17}
}

func (x *AiUsage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiUsage) GetCurrentValue() float64 {
	if x != nil {
		return x.CurrentValue
	}
	return 0
}

func (x *AiUsage) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLocationsWithQuotaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	// Candidate locations to check. If empty, checks all AI Services locations.
	Locations     []string            `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"`
	Requirements  []*QuotaRequirement `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsWithQuotaRequest) Reset() {
	*x = ListLocationsWithQuotaRequest{}
	mi := &file_ai_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsWithQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsWithQuotaRequest) ProtoMessage() {}

func (x *ListLocationsWithQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsWithQuotaRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsWithQuotaRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{18}
}

func (x *ListLocationsWithQuotaRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListLocationsWithQuotaRequest) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *ListLocationsWithQuotaRequest) GetRequirements() []*QuotaRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type QuotaRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsageName     string                 `protobuf:"bytes,1,opt,name=usage_name,json=usageName,proto3" json:"usage_name,omitempty"` // e.g. "OpenAI.Standard.gpt-4o"
	Capacity      float64                `protobuf:"fixed64,2,opt,name=capacity,proto3" json:"capacity,omitempty"`                  // minimum required remaining capacity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaRequirement) Reset() {
	*x = QuotaRequirement{}
	mi := &file_ai_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaRequirement) ProtoMessage() {}

func (x *QuotaRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaRequirement.ProtoReflect.Descriptor instead.
func (*QuotaRequirement) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{19}
}

func (x *QuotaRequirement) GetUsageName() string {
	if x != nil {
		return x.UsageName
	}
	return ""
}

func (x *QuotaRequirement) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type ListLocationsWithQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsWithQuotaResponse) Reset() {
	*x = ListLocationsWithQuotaResponse{}
	mi := &file_ai_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsWithQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsWithQuotaResponse) ProtoMessage() {}

func (x *ListLocationsWithQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsWithQuotaResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsWithQuotaResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{20}
}

func (x *ListLocationsWithQuotaResponse) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type ListSkuLocationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Kind           string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`                                     // e.g. "AIServices"
	SkuName        string                 `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`                // e.g. "S0"
	Tier           string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`                                     // e.g. "Standard"
	ResourceType   string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // e.g. "accounts"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSkuLocationsRequest) Reset() {
	*x = ListSkuLocationsRequest{}
	mi := &file_ai_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkuLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkuLocationsRequest) ProtoMessage() {}

func (x *ListSkuLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkuLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListSkuLocationsRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{21}
}

func (x *ListSkuLocationsRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ListSkuLocationsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ListSkuLocationsRequest) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *ListSkuLocationsRequest) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *ListSkuLocationsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type ListSkuLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSkuLocationsResponse) Reset() {
	*x = ListSkuLocationsResponse{}
	mi := &file_ai_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSkuLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSkuLocationsResponse) ProtoMessage() {}

func (x *ListSkuLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSkuLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListSkuLocationsResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{22}
}

func (x *ListSkuLocationsResponse) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type ResolveModelDeploymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// Preferred location. If the model lacks quota here, other locations are tried.
	PreferredLocation string `protobuf:"bytes,3,opt,name=preferred_location,json=preferredLocation,proto3" json:"preferred_location,omitempty"`
	// Preferred versions in priority order. Defaults to the model's default version.
	PreferredVersions []string `protobuf:"bytes,4,rep,name=preferred_versions,json=preferredVersions,proto3" json:"preferred_versions,omitempty"`
	// Preferred SKUs in priority order. Defaults to ["GlobalStandard", "DataZoneStandard", "Standard"].
	PreferredSkus []string `protobuf:"bytes,5,rep,name=preferred_skus,json=preferredSkus,proto3" json:"preferred_skus,omitempty"`
	// Minimum capacity required. Defaults to the SKU's default capacity.
	MinCapacity *int32 `protobuf:"varint,6,opt,name=min_capacity,json=minCapacity,proto3,oneof" json:"min_capacity,omitempty"`
	// Optional filter to constrain model search (capabilities, format, kind).
	Filter        *AiModelFilterOptions `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveModelDeploymentRequest) Reset() {
	*x = ResolveModelDeploymentRequest{}
	mi := &file_ai_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelDeploymentRequest) ProtoMessage() {}

func (x *ResolveModelDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelDeploymentRequest.ProtoReflect.Descriptor instead.
func (*ResolveModelDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveModelDeploymentRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ResolveModelDeploymentRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ResolveModelDeploymentRequest) GetPreferredLocation() string {
	if x != nil {
		return x.PreferredLocation
	}
	return ""
}

func (x *ResolveModelDeploymentRequest) GetPreferredVersions() []string {
	if x != nil {
		return x.PreferredVersions
	}
	return nil
}

func (x *ResolveModelDeploymentRequest) GetPreferredSkus() []string {
	if x != nil {
		return x.PreferredSkus
	}
	return nil
}

func (x *ResolveModelDeploymentRequest) GetMinCapacity() int32 {
	if x != nil && x.MinCapacity != nil {
		return *x.MinCapacity
	}
	return 0
}

func (x *ResolveModelDeploymentRequest) GetFilter() *AiModelFilterOptions {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ResolveModelDeploymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resolved deployment configuration (version, SKU, location, capacity).
	Deployment *GetModelDeploymentResponse `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	// Whether quota was validated and sufficient.
	QuotaValidated bool `protobuf:"varint,2,opt,name=quota_validated,json=quotaValidated,proto3" json:"quota_validated,omitempty"`
	// Available remaining capacity for this deployment's usage name in the resolved location.
	AvailableCapacity float64 `protobuf:"fixed64,3,opt,name=available_capacity,json=availableCapacity,proto3" json:"available_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveModelDeploymentResponse) Reset() {
	*x = ResolveModelDeploymentResponse{}
	mi := &file_ai_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelDeploymentResponse) ProtoMessage() {}

func (x *ResolveModelDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelDeploymentResponse.ProtoReflect.Descriptor instead.
func (*ResolveModelDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{24}
}

func (x *ResolveModelDeploymentResponse) GetDeployment() *GetModelDeploymentResponse {
	if x != nil {
		return x.Deployment
	}
	return nil
}

func (x *ResolveModelDeploymentResponse) GetQuotaValidated() bool {
	if x != nil {
		return x.QuotaValidated
	}
	return false
}

func (x *ResolveModelDeploymentResponse) GetAvailableCapacity() float64 {
	if x != nil {
		return x.AvailableCapacity
	}
	return 0
}

type ValidateModelAvailabilityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ModelName      string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Location       string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Optional filter to constrain alternatives (capabilities, format, kind).
	Filter *AiModelFilterOptions `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// Maximum number of alternatives to return (default: 10).
	MaxAlternatives *int32 `protobuf:"varint,5,opt,name=max_alternatives,json=maxAlternatives,proto3,oneof" json:"max_alternatives,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateModelAvailabilityRequest) Reset() {
	*x = ValidateModelAvailabilityRequest{}
	mi := &file_ai_model_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateModelAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateModelAvailabilityRequest) ProtoMessage() {}

func (x *ValidateModelAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateModelAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*ValidateModelAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{25}
}

func (x *ValidateModelAvailabilityRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ValidateModelAvailabilityRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ValidateModelAvailabilityRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ValidateModelAvailabilityRequest) GetFilter() *AiModelFilterOptions {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ValidateModelAvailabilityRequest) GetMaxAlternatives() int32 {
	if x != nil && x.MaxAlternatives != nil {
		return *x.MaxAlternatives
	}
	return 0
}

type ValidateModelAvailabilityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the model is available in the requested location.
	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// Locations where this model IS available (if not available in requested location).
	AlternativeLocations []string `protobuf:"bytes,2,rep,name=alternative_locations,json=alternativeLocations,proto3" json:"alternative_locations,omitempty"`
	// Other models available in the requested location (if model is not available there).
	AlternativeModels []string `protobuf:"bytes,3,rep,name=alternative_models,json=alternativeModels,proto3" json:"alternative_models,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidateModelAvailabilityResponse) Reset() {
	*x = ValidateModelAvailabilityResponse{}
	mi := &file_ai_model_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateModelAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateModelAvailabilityResponse) ProtoMessage() {}

func (x *ValidateModelAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_model_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateModelAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*ValidateModelAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_ai_model_proto_rawDescGZIP(), []int{26}
}

func (x *ValidateModelAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ValidateModelAvailabilityResponse) GetAlternativeLocations() []string {
	if x != nil {
		return x.AlternativeLocations
	}
	return nil
}

func (x *ValidateModelAvailabilityResponse) GetAlternativeModels() []string {
	if x != nil {
		return x.AlternativeModels
	}
	return nil
}

var File_ai_model_proto protoreflect.FileDescriptor

const file_ai_model_proto_rawDesc = "" +
	"\n" +
	"\x0eai_model.proto\x12\x06azdext\"\xa4\x01\n" +
	"\x14AiModelFilterOptions\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bstatuses\x18\x02 \x03(\tR\bstatuses\x12\x18\n" +
	"\aformats\x18\x03 \x03(\tR\aformats\x12\x14\n" +
	"\x05kinds\x18\x04 \x03(\tR\x05kinds\x12\x1c\n" +
	"\tlocations\x18\x05 \x03(\tR\tlocations\"\xa0\x01\n" +
	"\x11ListModelsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1f\n" +
	"\blocation\x18\x02 \x01(\tH\x00R\blocation\x88\x01\x01\x124\n" +
	"\x06filter\x18\x03 \x01(\v2\x1c.azdext.AiModelFilterOptionsR\x06filterB\v\n" +
	"\t_location\"=\n" +
	"\x12ListModelsResponse\x12'\n" +
	"\x06models\x18\x01 \x03(\v2\x0f.azdext.AiModelR\x06models\"\xdb\x01\n" +
	"\aAiModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12V\n" +
	"\x13details_by_location\x18\x02 \x03(\v2&.azdext.AiModel.DetailsByLocationEntryR\x11detailsByLocation\x1ad\n" +
	"\x16DetailsByLocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.azdext.AiModelLocationDetailsR\x05value:\x028\x01\"L\n" +
	"\x16AiModelLocationDetails\x122\n" +
	"\bversions\x18\x01 \x03(\v2\x16.azdext.AiModelVersionR\bversions\"\xe6\x02\n" +
	"\x0eAiModelVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12,\n" +
	"\x12is_default_version\x18\x04 \x01(\bR\x10isDefaultVersion\x12)\n" +
	"\x10lifecycle_status\x18\x05 \x01(\tR\x0flifecycleStatus\x12L\n" +
	"\fcapabilities\x18\x06 \x03(\v2(.azdext.AiModelVersion.CapabilitiesEntryR\fcapabilities\x12&\n" +
	"\x04skus\x18\a \x03(\v2\x12.azdext.AiModelSkuR\x04skus\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\n" +
	"AiModelSku\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x02 \x01(\tR\tusageName\x126\n" +
	"\bcapacity\x18\x03 \x01(\v2\x1a.azdext.AiModelSkuCapacityR\bcapacity\"\x81\x01\n" +
	"\x12AiModelSkuCapacity\x12#\n" +
	"\rdefault_value\x18\x01 \x01(\x05R\fdefaultValue\x12\x18\n" +
	"\amaximum\x18\x02 \x01(\x05R\amaximum\x12\x18\n" +
	"\aminimum\x18\x03 \x01(\x05R\aminimum\x12\x12\n" +
	"\x04step\x18\x04 \x01(\x05R\x04step\"~\n" +
	"\x18ListModelVersionsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"`\n" +
	"\x19ListModelVersionsResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\tR\bversions\x12'\n" +
	"\x0fdefault_version\x18\x02 \x01(\tR\x0edefaultVersion\"\x94\x01\n" +
	"\x14ListModelSkusRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"+\n" +
	"\x15ListModelSkusResponse\x12\x12\n" +
	"\x04skus\x18\x01 \x03(\tR\x04skus\"\xea\x01\n" +
	"\x19GetModelDeploymentRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12/\n" +
	"\x13preferred_locations\x18\x03 \x03(\tR\x12preferredLocations\x12-\n" +
	"\x12preferred_versions\x18\x04 \x03(\tR\x11preferredVersions\x12%\n" +
	"\x0epreferred_skus\x18\x05 \x03(\tR\rpreferredSkus\"\xae\x01\n" +
	"\x1aGetModelDeploymentResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12.\n" +
	"\x03sku\x18\x05 \x01(\v2\x1c.azdext.AiModelDeploymentSkuR\x03sku\"e\n" +
	"\x14AiModelDeploymentSku\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x02 \x01(\tR\tusageName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\"X\n" +
	"\x11ListUsagesRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"=\n" +
	"\x12ListUsagesResponse\x12'\n" +
	"\x06usages\x18\x01 \x03(\v2\x0f.azdext.AiUsageR\x06usages\"X\n" +
	"\aAiUsage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rcurrent_value\x18\x02 \x01(\x01R\fcurrentValue\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x01R\x05limit\"\xa4\x01\n" +
	"\x1dListLocationsWithQuotaRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1c\n" +
	"\tlocations\x18\x02 \x03(\tR\tlocations\x12<\n" +
	"\frequirements\x18\x03 \x03(\v2\x18.azdext.QuotaRequirementR\frequirements\"M\n" +
	"\x10QuotaRequirement\x12\x1d\n" +
	"\n" +
	"usage_name\x18\x01 \x01(\tR\tusageName\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x01R\bcapacity\">\n" +
	"\x1eListLocationsWithQuotaResponse\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\"\xaa\x01\n" +
	"\x17ListSkuLocationsRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x19\n" +
	"\bsku_name\x18\x03 \x01(\tR\askuName\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\"8\n" +
	"\x18ListSkuLocationsResponse\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\"\xdb\x02\n" +
	"\x1dResolveModelDeploymentRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12-\n" +
	"\x12preferred_location\x18\x03 \x01(\tR\x11preferredLocation\x12-\n" +
	"\x12preferred_versions\x18\x04 \x03(\tR\x11preferredVersions\x12%\n" +
	"\x0epreferred_skus\x18\x05 \x03(\tR\rpreferredSkus\x12&\n" +
	"\fmin_capacity\x18\x06 \x01(\x05H\x00R\vminCapacity\x88\x01\x01\x124\n" +
	"\x06filter\x18\a \x01(\v2\x1c.azdext.AiModelFilterOptionsR\x06filterB\x0f\n" +
	"\r_min_capacity\"\xbc\x01\n" +
	"\x1eResolveModelDeploymentResponse\x12B\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\".azdext.GetModelDeploymentResponseR\n" +
	"deployment\x12'\n" +
	"\x0fquota_validated\x18\x02 \x01(\bR\x0equotaValidated\x12-\n" +
	"\x12available_capacity\x18\x03 \x01(\x01R\x11availableCapacity\"\x81\x02\n" +
	" ValidateModelAvailabilityRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x124\n" +
	"\x06filter\x18\x04 \x01(\v2\x1c.azdext.AiModelFilterOptionsR\x06filter\x12.\n" +
	"\x10max_alternatives\x18\x05 \x01(\x05H\x00R\x0fmaxAlternatives\x88\x01\x01B\x13\n" +
	"\x11_max_alternatives\"\xa5\x01\n" +
	"!ValidateModelAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x123\n" +
	"\x15alternative_locations\x18\x02 \x03(\tR\x14alternativeLocations\x12-\n" +
	"\x12alternative_models\x18\x03 \x03(\tR\x11alternativeModels2\xba\x06\n" +
	"\x0eAiModelService\x12C\n" +
	"\n" +
	"ListModels\x12\x19.azdext.ListModelsRequest\x1a\x1a.azdext.ListModelsResponse\x12X\n" +
	"\x11ListModelVersions\x12 .azdext.ListModelVersionsRequest\x1a!.azdext.ListModelVersionsResponse\x12L\n" +
	"\rListModelSkus\x12\x1c.azdext.ListModelSkusRequest\x1a\x1d.azdext.ListModelSkusResponse\x12[\n" +
	"\x12GetModelDeployment\x12!.azdext.GetModelDeploymentRequest\x1a\".azdext.GetModelDeploymentResponse\x12g\n" +
	"\x16ResolveModelDeployment\x12%.azdext.ResolveModelDeploymentRequest\x1a&.azdext.ResolveModelDeploymentResponse\x12p\n" +
	"\x19ValidateModelAvailability\x12(.azdext.ValidateModelAvailabilityRequest\x1a).azdext.ValidateModelAvailabilityResponse\x12C\n" +
	"\n" +
	"ListUsages\x12\x19.azdext.ListUsagesRequest\x1a\x1a.azdext.ListUsagesResponse\x12g\n" +
	"\x16ListLocationsWithQuota\x12%.azdext.ListLocationsWithQuotaRequest\x1a&.azdext.ListLocationsWithQuotaResponse\x12U\n" +
	"\x10ListSkuLocations\x12\x1f.azdext.ListSkuLocationsRequest\x1a .azdext.ListSkuLocationsResponseB/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_ai_model_proto_rawDescOnce sync.Once
	file_ai_model_proto_rawDescData []byte
)

func file_ai_model_proto_rawDescGZIP() []byte {
	file_ai_model_proto_rawDescOnce.Do(func() {
		file_ai_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_model_proto_rawDesc), len(file_ai_model_proto_rawDesc)))
	})
	return file_ai_model_proto_rawDescData
}

var file_ai_model_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_ai_model_proto_goTypes = []any{
	(*AiModelFilterOptions)(nil),              // 0: azdext.AiModelFilterOptions
	(*ListModelsRequest)(nil),                 // 1: azdext.ListModelsRequest
	(*ListModelsResponse)(nil),                // 2: azdext.ListModelsResponse
	(*AiModel)(nil),                           // 3: azdext.AiModel
	(*AiModelLocationDetails)(nil),            // 4: azdext.AiModelLocationDetails
	(*AiModelVersion)(nil),                    // 5: azdext.AiModelVersion
	(*AiModelSku)(nil),                        // 6: azdext.AiModelSku
	(*AiModelSkuCapacity)(nil),                // 7: azdext.AiModelSkuCapacity
	(*ListModelVersionsRequest)(nil),          // 8: azdext.ListModelVersionsRequest
	(*ListModelVersionsResponse)(nil),         // 9: azdext.ListModelVersionsResponse
	(*ListModelSkusRequest)(nil),              // 10: azdext.ListModelSkusRequest
	(*ListModelSkusResponse)(nil),             // 11: azdext.ListModelSkusResponse
	(*GetModelDeploymentRequest)(nil),         // 12: azdext.GetModelDeploymentRequest
	(*GetModelDeploymentResponse)(nil),        // 13: azdext.GetModelDeploymentResponse
	(*AiModelDeploymentSku)(nil),              // 14: azdext.AiModelDeploymentSku
	(*ListUsagesRequest)(nil),                 // 15: azdext.ListUsagesRequest
	(*ListUsagesResponse)(nil),                // 16: azdext.ListUsagesResponse
	(*AiUsage)(nil),                           // 17: azdext.AiUsage
	(*ListLocationsWithQuotaRequest)(nil),     // 18: azdext.ListLocationsWithQuotaRequest
	(*QuotaRequirement)(nil),                  // 19: azdext.QuotaRequirement
	(*ListLocationsWithQuotaResponse)(nil),    // 20: azdext.ListLocationsWithQuotaResponse
	(*ListSkuLocationsRequest)(nil),           // 21: azdext.ListSkuLocationsRequest
	(*ListSkuLocationsResponse)(nil),          // 22: azdext.ListSkuLocationsResponse
	(*ResolveModelDeploymentRequest)(nil),     // 23: azdext.ResolveModelDeploymentRequest
	(*ResolveModelDeploymentResponse)(nil),    // 24: azdext.ResolveModelDeploymentResponse
	(*ValidateModelAvailabilityRequest)(nil),  // 25: azdext.ValidateModelAvailabilityRequest
	(*ValidateModelAvailabilityResponse)(nil), // 26: azdext.ValidateModelAvailabilityResponse
	nil, // 27: azdext.AiModel.DetailsByLocationEntry
	nil, // 28: azdext.AiModelVersion.CapabilitiesEntry
}
var file_ai_model_proto_depIdxs = []int32{
	0,  // 0: azdext.ListModelsRequest.filter:type_name -> azdext.AiModelFilterOptions
	3,  // 1: azdext.ListModelsResponse.models:type_name -> azdext.AiModel
	27, // 2: azdext.AiModel.details_by_location:type_name -> azdext.AiModel.DetailsByLocationEntry
	5,  // 3: azdext.AiModelLocationDetails.versions:type_name -> azdext.AiModelVersion
	28, // 4: azdext.AiModelVersion.capabilities:type_name -> azdext.AiModelVersion.CapabilitiesEntry
	6,  // 5: azdext.AiModelVersion.skus:type_name -> azdext.AiModelSku
	7,  // 6: azdext.AiModelSku.capacity:type_name -> azdext.AiModelSkuCapacity
	14, // 7: azdext.GetModelDeploymentResponse.sku:type_name -> azdext.AiModelDeploymentSku
	17, // 8: azdext.ListUsagesResponse.usages:type_name -> azdext.AiUsage
	19, // 9: azdext.ListLocationsWithQuotaRequest.requirements:type_name -> azdext.QuotaRequirement
	0,  // 10: azdext.ResolveModelDeploymentRequest.filter:type_name -> azdext.AiModelFilterOptions
	13, // 11: azdext.ResolveModelDeploymentResponse.deployment:type_name -> azdext.GetModelDeploymentResponse
	0,  // 12: azdext.ValidateModelAvailabilityRequest.filter:type_name -> azdext.AiModelFilterOptions
	4,  // 13: azdext.AiModel.DetailsByLocationEntry.value:type_name -> azdext.AiModelLocationDetails
	1,  // 14: azdext.AiModelService.ListModels:input_type -> azdext.ListModelsRequest
	8,  // 15: azdext.AiModelService.ListModelVersions:input_type -> azdext.ListModelVersionsRequest
	10, // 16: azdext.AiModelService.ListModelSkus:input_type -> azdext.ListModelSkusRequest
	12, // 17: azdext.AiModelService.GetModelDeployment:input_type -> azdext.GetModelDeploymentRequest
	23, // 18: azdext.AiModelService.ResolveModelDeployment:input_type -> azdext.ResolveModelDeploymentRequest
	25, // 19: azdext.AiModelService.ValidateModelAvailability:input_type -> azdext.ValidateModelAvailabilityRequest
	15, // 20: azdext.AiModelService.ListUsages:input_type -> azdext.ListUsagesRequest
	18, // 21: azdext.AiModelService.ListLocationsWithQuota:input_type -> azdext.ListLocationsWithQuotaRequest
	21, // 22: azdext.AiModelService.ListSkuLocations:input_type -> azdext.ListSkuLocationsRequest
	2,  // 23: azdext.AiModelService.ListModels:output_type -> azdext.ListModelsResponse
	9,  // 24: azdext.AiModelService.ListModelVersions:output_type -> azdext.ListModelVersionsResponse
	11, // 25: azdext.AiModelService.ListModelSkus:output_type -> azdext.ListModelSkusResponse
	13, // 26: azdext.AiModelService.GetModelDeployment:output_type -> azdext.GetModelDeploymentResponse
	24, // 27: azdext.AiModelService.ResolveModelDeployment:output_type -> azdext.ResolveModelDeploymentResponse
	26, // 28: azdext.AiModelService.ValidateModelAvailability:output_type -> azdext.ValidateModelAvailabilityResponse
	16, // 29: azdext.AiModelService.ListUsages:output_type -> azdext.ListUsagesResponse
	20, // 30: azdext.AiModelService.ListLocationsWithQuota:output_type -> azdext.ListLocationsWithQuotaResponse
	22, // 31: azdext.AiModelService.ListSkuLocations:output_type -> azdext.ListSkuLocationsResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_ai_model_proto_init() }
func file_ai_model_proto_init() {
	if File_ai_model_proto != nil {
		return
	}
	file_ai_model_proto_msgTypes[1].OneofWrappers = []any{}
	file_ai_model_proto_msgTypes[23].OneofWrappers = []any{}
	file_ai_model_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_model_proto_rawDesc), len(file_ai_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_model_proto_goTypes,
		DependencyIndexes: file_ai_model_proto_depIdxs,
		MessageInfos:      file_ai_model_proto_msgTypes,
	}.Build()
	File_ai_model_proto = out.File
	file_ai_model_proto_goTypes = nil
	file_ai_model_proto_depIdxs = nil
}
