// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: service_target.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope for all possible service target messages (requests and responses)
type ServiceTargetMessage struct {
	state     protoimpl.MessageState     `protogen:"open.v1"`
	RequestId string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error     *ServiceTargetErrorMessage `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ServiceTargetMessage_RegisterServiceTargetRequest
	//	*ServiceTargetMessage_RegisterServiceTargetResponse
	//	*ServiceTargetMessage_GetTargetResourceRequest
	//	*ServiceTargetMessage_GetTargetResourceResponse
	//	*ServiceTargetMessage_DeployRequest
	//	*ServiceTargetMessage_DeployResponse
	//	*ServiceTargetMessage_ProgressMessage
	MessageType   isServiceTargetMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetMessage) Reset() {
	*x = ServiceTargetMessage{}
	mi := &file_service_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetMessage) ProtoMessage() {}

func (x *ServiceTargetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetMessage.ProtoReflect.Descriptor instead.
func (*ServiceTargetMessage) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceTargetMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceTargetMessage) GetError() *ServiceTargetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceTargetMessage) GetMessageType() isServiceTargetMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ServiceTargetMessage) GetRegisterServiceTargetRequest() *RegisterServiceTargetRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_RegisterServiceTargetRequest); ok {
			return x.RegisterServiceTargetRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetRegisterServiceTargetResponse() *RegisterServiceTargetResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_RegisterServiceTargetResponse); ok {
			return x.RegisterServiceTargetResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetGetTargetResourceRequest() *GetTargetResourceRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_GetTargetResourceRequest); ok {
			return x.GetTargetResourceRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetGetTargetResourceResponse() *GetTargetResourceResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_GetTargetResourceResponse); ok {
			return x.GetTargetResourceResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetDeployRequest() *ServiceTargetDeployRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_DeployRequest); ok {
			return x.DeployRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetDeployResponse() *ServiceTargetDeployResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_DeployResponse); ok {
			return x.DeployResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetProgressMessage() *ServiceTargetProgressMessage {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_ProgressMessage); ok {
			return x.ProgressMessage
		}
	}
	return nil
}

type isServiceTargetMessage_MessageType interface {
	isServiceTargetMessage_MessageType()
}

type ServiceTargetMessage_RegisterServiceTargetRequest struct {
	RegisterServiceTargetRequest *RegisterServiceTargetRequest `protobuf:"bytes,2,opt,name=register_service_target_request,json=registerServiceTargetRequest,proto3,oneof"`
}

type ServiceTargetMessage_RegisterServiceTargetResponse struct {
	RegisterServiceTargetResponse *RegisterServiceTargetResponse `protobuf:"bytes,3,opt,name=register_service_target_response,json=registerServiceTargetResponse,proto3,oneof"`
}

type ServiceTargetMessage_GetTargetResourceRequest struct {
	// ServiceTargetNameRequest name_request = 4;
	// ServiceTargetNameResponse name_response = 5;
	// ServiceTargetInitializeRequest initialize_request = 6;
	// ServiceTargetInitializeResponse initialize_response = 7;
	// ServiceTargetStateRequest state_request = 8;
	// ServiceTargetStateResponse state_response = 9;
	GetTargetResourceRequest *GetTargetResourceRequest `protobuf:"bytes,10,opt,name=get_target_resource_request,json=getTargetResourceRequest,proto3,oneof"`
}

type ServiceTargetMessage_GetTargetResourceResponse struct {
	GetTargetResourceResponse *GetTargetResourceResponse `protobuf:"bytes,11,opt,name=get_target_resource_response,json=getTargetResourceResponse,proto3,oneof"`
}

type ServiceTargetMessage_DeployRequest struct {
	DeployRequest *ServiceTargetDeployRequest `protobuf:"bytes,12,opt,name=deploy_request,json=deployRequest,proto3,oneof"`
}

type ServiceTargetMessage_DeployResponse struct {
	DeployResponse *ServiceTargetDeployResponse `protobuf:"bytes,13,opt,name=deploy_response,json=deployResponse,proto3,oneof"`
}

type ServiceTargetMessage_ProgressMessage struct {
	ProgressMessage *ServiceTargetProgressMessage `protobuf:"bytes,14,opt,name=progress_message,json=progressMessage,proto3,oneof"`
}

func (*ServiceTargetMessage_RegisterServiceTargetRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_RegisterServiceTargetResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_GetTargetResourceRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_GetTargetResourceResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_DeployRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_DeployResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_ProgressMessage) isServiceTargetMessage_MessageType() {}

// State
type ServiceTargetState struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Outputs       map[string]*ServiceTargetOutputParameter `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     []*ServiceTargetResource                 `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetState) Reset() {
	*x = ServiceTargetState{}
	mi := &file_service_target_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetState) ProtoMessage() {}

func (x *ServiceTargetState) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetState.ProtoReflect.Descriptor instead.
func (*ServiceTargetState) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceTargetState) GetOutputs() map[string]*ServiceTargetOutputParameter {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ServiceTargetState) GetResources() []*ServiceTargetResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// InputParameter
type ServiceTargetInputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInputParameter) Reset() {
	*x = ServiceTargetInputParameter{}
	mi := &file_service_target_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInputParameter) ProtoMessage() {}

func (x *ServiceTargetInputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInputParameter.ProtoReflect.Descriptor instead.
func (*ServiceTargetInputParameter) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceTargetInputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceTargetInputParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ServiceTargetInputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OutputParameter
type ServiceTargetOutputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetOutputParameter) Reset() {
	*x = ServiceTargetOutputParameter{}
	mi := &file_service_target_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetOutputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetOutputParameter) ProtoMessage() {}

func (x *ServiceTargetOutputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetOutputParameter.ProtoReflect.Descriptor instead.
func (*ServiceTargetOutputParameter) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceTargetOutputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceTargetOutputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Resource
type ServiceTargetResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetResource) Reset() {
	*x = ServiceTargetResource{}
	mi := &file_service_target_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetResource) ProtoMessage() {}

func (x *ServiceTargetResource) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetResource.ProtoReflect.Descriptor instead.
func (*ServiceTargetResource) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceTargetResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServiceTargetNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetNameRequest) Reset() {
	*x = ServiceTargetNameRequest{}
	mi := &file_service_target_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetNameRequest) ProtoMessage() {}

func (x *ServiceTargetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetNameRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetNameRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{5}
}

type ServiceTargetNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetNameResponse) Reset() {
	*x = ServiceTargetNameResponse{}
	mi := &file_service_target_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetNameResponse) ProtoMessage() {}

func (x *ServiceTargetNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetNameResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetNameResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceTargetNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceTargetInitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Options       *ServiceTargetOptions  `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInitializeRequest) Reset() {
	*x = ServiceTargetInitializeRequest{}
	mi := &file_service_target_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInitializeRequest) ProtoMessage() {}

func (x *ServiceTargetInitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInitializeRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetInitializeRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceTargetInitializeRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *ServiceTargetInitializeRequest) GetOptions() *ServiceTargetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ServiceTargetInitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInitializeResponse) Reset() {
	*x = ServiceTargetInitializeResponse{}
	mi := &file_service_target_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInitializeResponse) ProtoMessage() {}

func (x *ServiceTargetInitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInitializeResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetInitializeResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{8}
}

type ServiceTargetStateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Options       *ServiceTargetStateOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateRequest) Reset() {
	*x = ServiceTargetStateRequest{}
	mi := &file_service_target_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateRequest) ProtoMessage() {}

func (x *ServiceTargetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceTargetStateRequest) GetOptions() *ServiceTargetStateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ServiceTargetStateResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StateResult   *ServiceTargetStateResult `protobuf:"bytes,1,opt,name=state_result,json=stateResult,proto3" json:"state_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateResponse) Reset() {
	*x = ServiceTargetStateResponse{}
	mi := &file_service_target_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateResponse) ProtoMessage() {}

func (x *ServiceTargetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceTargetStateResponse) GetStateResult() *ServiceTargetStateResult {
	if x != nil {
		return x.StateResult
	}
	return nil
}

// Core options and result wrappers
type ServiceTargetOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Provider              string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Path                  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Module                string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	DeploymentStacks      map[string]string      `protobuf:"bytes,4,rep,name=deployment_stacks,json=deploymentStacks,proto3" json:"deployment_stacks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IgnoreDeploymentState bool                   `protobuf:"varint,5,opt,name=ignore_deployment_state,json=ignoreDeploymentState,proto3" json:"ignore_deployment_state,omitempty"`
	Config                *structpb.Struct       `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServiceTargetOptions) Reset() {
	*x = ServiceTargetOptions{}
	mi := &file_service_target_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetOptions) ProtoMessage() {}

func (x *ServiceTargetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetOptions.ProtoReflect.Descriptor instead.
func (*ServiceTargetOptions) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceTargetOptions) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ServiceTargetOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServiceTargetOptions) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ServiceTargetOptions) GetDeploymentStacks() map[string]string {
	if x != nil {
		return x.DeploymentStacks
	}
	return nil
}

func (x *ServiceTargetOptions) GetIgnoreDeploymentState() bool {
	if x != nil {
		return x.IgnoreDeploymentState
	}
	return false
}

func (x *ServiceTargetOptions) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ServiceTargetStateOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Add fields as needed
	Hint          string `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateOptions) Reset() {
	*x = ServiceTargetStateOptions{}
	mi := &file_service_target_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateOptions) ProtoMessage() {}

func (x *ServiceTargetStateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateOptions.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateOptions) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceTargetStateOptions) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type ServiceTargetStateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ServiceTargetState    `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateResult) Reset() {
	*x = ServiceTargetStateResult{}
	mi := &file_service_target_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateResult) ProtoMessage() {}

func (x *ServiceTargetStateResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateResult.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateResult) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceTargetStateResult) GetState() *ServiceTargetState {
	if x != nil {
		return x.State
	}
	return nil
}

type RegisterServiceTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // unique identifier for the provider
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceTargetRequest) Reset() {
	*x = RegisterServiceTargetRequest{}
	mi := &file_service_target_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceTargetRequest) ProtoMessage() {}

func (x *RegisterServiceTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceTargetRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceTargetRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterServiceTargetRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RegisterServiceTargetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceTargetResponse) Reset() {
	*x = RegisterServiceTargetResponse{}
	mi := &file_service_target_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceTargetResponse) ProtoMessage() {}

func (x *RegisterServiceTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceTargetResponse.ProtoReflect.Descriptor instead.
func (*RegisterServiceTargetResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{15}
}

type ServiceTargetErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetErrorMessage) Reset() {
	*x = ServiceTargetErrorMessage{}
	mi := &file_service_target_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetErrorMessage) ProtoMessage() {}

func (x *ServiceTargetErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetErrorMessage.ProtoReflect.Descriptor instead.
func (*ServiceTargetErrorMessage) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceTargetErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceTargetErrorMessage) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// GetTargetResource request and response
type GetTargetResourceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ServiceConfig  *ServiceTargetConfig   `protobuf:"bytes,2,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTargetResourceRequest) Reset() {
	*x = GetTargetResourceRequest{}
	mi := &file_service_target_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetResourceRequest) ProtoMessage() {}

func (x *GetTargetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetTargetResourceRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{17}
}

func (x *GetTargetResourceRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetTargetResourceRequest) GetServiceConfig() *ServiceTargetConfig {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

type GetTargetResourceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetResource *TargetResource        `protobuf:"bytes,1,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTargetResourceResponse) Reset() {
	*x = GetTargetResourceResponse{}
	mi := &file_service_target_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetResourceResponse) ProtoMessage() {}

func (x *GetTargetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetTargetResourceResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{18}
}

func (x *GetTargetResourceResponse) GetTargetResource() *TargetResource {
	if x != nil {
		return x.TargetResource
	}
	return nil
}

// ServiceTargetConfig represents the service configuration needed for target resource resolution
type ServiceTargetConfig struct {
	state                    protoimpl.MessageState     `protogen:"open.v1"`
	Name                     string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Host                     string                     `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	ProjectName              string                     `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ResourceGroupName        *ResourceGroupNameTemplate `protobuf:"bytes,4,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ProjectResourceGroupName *ResourceGroupNameTemplate `protobuf:"bytes,5,opt,name=project_resource_group_name,json=projectResourceGroupName,proto3" json:"project_resource_group_name,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ServiceTargetConfig) Reset() {
	*x = ServiceTargetConfig{}
	mi := &file_service_target_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetConfig) ProtoMessage() {}

func (x *ServiceTargetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetConfig.ProtoReflect.Descriptor instead.
func (*ServiceTargetConfig) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{19}
}

func (x *ServiceTargetConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceTargetConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceTargetConfig) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ServiceTargetConfig) GetResourceGroupName() *ResourceGroupNameTemplate {
	if x != nil {
		return x.ResourceGroupName
	}
	return nil
}

func (x *ServiceTargetConfig) GetProjectResourceGroupName() *ResourceGroupNameTemplate {
	if x != nil {
		return x.ProjectResourceGroupName
	}
	return nil
}

// ResourceGroupNameTemplate represents a resource group name template
type ResourceGroupNameTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	IsEmpty       bool                   `protobuf:"varint,2,opt,name=is_empty,json=isEmpty,proto3" json:"is_empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceGroupNameTemplate) Reset() {
	*x = ResourceGroupNameTemplate{}
	mi := &file_service_target_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceGroupNameTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceGroupNameTemplate) ProtoMessage() {}

func (x *ResourceGroupNameTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceGroupNameTemplate.ProtoReflect.Descriptor instead.
func (*ResourceGroupNameTemplate) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceGroupNameTemplate) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ResourceGroupNameTemplate) GetIsEmpty() bool {
	if x != nil {
		return x.IsEmpty
	}
	return false
}

// TargetResource represents the resolved target resource
type TargetResource struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId    string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	ResourceGroupName string                 `protobuf:"bytes,2,opt,name=resource_group_name,json=resourceGroupName,proto3" json:"resource_group_name,omitempty"`
	ResourceName      string                 `protobuf:"bytes,3,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType      string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TargetResource) Reset() {
	*x = TargetResource{}
	mi := &file_service_target_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetResource) ProtoMessage() {}

func (x *TargetResource) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetResource.ProtoReflect.Descriptor instead.
func (*TargetResource) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{21}
}

func (x *TargetResource) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *TargetResource) GetResourceGroupName() string {
	if x != nil {
		return x.ResourceGroupName
	}
	return ""
}

func (x *TargetResource) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *TargetResource) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

// Deploy request and response
type ServiceTargetDeployRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	ServiceConfig  *ServiceTargetConfig        `protobuf:"bytes,1,opt,name=service_config,json=serviceConfig,proto3" json:"service_config,omitempty"`
	ServicePackage *ServiceTargetPackageResult `protobuf:"bytes,2,opt,name=service_package,json=servicePackage,proto3" json:"service_package,omitempty"`
	TargetResource *TargetResource             `protobuf:"bytes,3,opt,name=target_resource,json=targetResource,proto3" json:"target_resource,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServiceTargetDeployRequest) Reset() {
	*x = ServiceTargetDeployRequest{}
	mi := &file_service_target_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetDeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetDeployRequest) ProtoMessage() {}

func (x *ServiceTargetDeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetDeployRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetDeployRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{22}
}

func (x *ServiceTargetDeployRequest) GetServiceConfig() *ServiceTargetConfig {
	if x != nil {
		return x.ServiceConfig
	}
	return nil
}

func (x *ServiceTargetDeployRequest) GetServicePackage() *ServiceTargetPackageResult {
	if x != nil {
		return x.ServicePackage
	}
	return nil
}

func (x *ServiceTargetDeployRequest) GetTargetResource() *TargetResource {
	if x != nil {
		return x.TargetResource
	}
	return nil
}

type ServiceTargetDeployResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	DeployResult  *ServiceTargetDeployResult `protobuf:"bytes,1,opt,name=deploy_result,json=deployResult,proto3" json:"deploy_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetDeployResponse) Reset() {
	*x = ServiceTargetDeployResponse{}
	mi := &file_service_target_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetDeployResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetDeployResponse) ProtoMessage() {}

func (x *ServiceTargetDeployResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetDeployResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetDeployResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{23}
}

func (x *ServiceTargetDeployResponse) GetDeployResult() *ServiceTargetDeployResult {
	if x != nil {
		return x.DeployResult
	}
	return nil
}

// ServiceTargetPackageResult represents the package result for deployment
type ServiceTargetPackageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackagePath   string                 `protobuf:"bytes,1,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	Details       map[string]string      `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetPackageResult) Reset() {
	*x = ServiceTargetPackageResult{}
	mi := &file_service_target_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetPackageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetPackageResult) ProtoMessage() {}

func (x *ServiceTargetPackageResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetPackageResult.ProtoReflect.Descriptor instead.
func (*ServiceTargetPackageResult) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{24}
}

func (x *ServiceTargetPackageResult) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *ServiceTargetPackageResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// ServiceTargetDeployResult represents the result of a deployment operation
type ServiceTargetDeployResult struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Package          *ServiceTargetPackageResult `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	TargetResourceId string                      `protobuf:"bytes,2,opt,name=target_resource_id,json=targetResourceId,proto3" json:"target_resource_id,omitempty"`
	Kind             string                      `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Endpoints        []string                    `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Details          string                      `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceTargetDeployResult) Reset() {
	*x = ServiceTargetDeployResult{}
	mi := &file_service_target_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetDeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetDeployResult) ProtoMessage() {}

func (x *ServiceTargetDeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetDeployResult.ProtoReflect.Descriptor instead.
func (*ServiceTargetDeployResult) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{25}
}

func (x *ServiceTargetDeployResult) GetPackage() *ServiceTargetPackageResult {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *ServiceTargetDeployResult) GetTargetResourceId() string {
	if x != nil {
		return x.TargetResourceId
	}
	return ""
}

func (x *ServiceTargetDeployResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ServiceTargetDeployResult) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ServiceTargetDeployResult) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// ServiceTargetProgressMessage represents a progress update from an extension
type ServiceTargetProgressMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetProgressMessage) Reset() {
	*x = ServiceTargetProgressMessage{}
	mi := &file_service_target_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetProgressMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetProgressMessage) ProtoMessage() {}

func (x *ServiceTargetProgressMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetProgressMessage.ProtoReflect.Descriptor instead.
func (*ServiceTargetProgressMessage) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{26}
}

func (x *ServiceTargetProgressMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceTargetProgressMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceTargetProgressMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_service_target_proto protoreflect.FileDescriptor

const file_service_target_proto_rawDesc = "" +
	"\n" +
	"\x14service_target.proto\x12\x06azdext\x1a$include/google/protobuf/struct.proto\"\x98\x06\n" +
	"\x14ServiceTargetMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\x05error\x18c \x01(\v2!.azdext.ServiceTargetErrorMessageR\x05error\x12m\n" +
	"\x1fregister_service_target_request\x18\x02 \x01(\v2$.azdext.RegisterServiceTargetRequestH\x00R\x1cregisterServiceTargetRequest\x12p\n" +
	" register_service_target_response\x18\x03 \x01(\v2%.azdext.RegisterServiceTargetResponseH\x00R\x1dregisterServiceTargetResponse\x12a\n" +
	"\x1bget_target_resource_request\x18\n" +
	" \x01(\v2 .azdext.GetTargetResourceRequestH\x00R\x18getTargetResourceRequest\x12d\n" +
	"\x1cget_target_resource_response\x18\v \x01(\v2!.azdext.GetTargetResourceResponseH\x00R\x19getTargetResourceResponse\x12K\n" +
	"\x0edeploy_request\x18\f \x01(\v2\".azdext.ServiceTargetDeployRequestH\x00R\rdeployRequest\x12N\n" +
	"\x0fdeploy_response\x18\r \x01(\v2#.azdext.ServiceTargetDeployResponseH\x00R\x0edeployResponse\x12Q\n" +
	"\x10progress_message\x18\x0e \x01(\v2$.azdext.ServiceTargetProgressMessageH\x00R\x0fprogressMessageB\x0e\n" +
	"\fmessage_type\"\xf6\x01\n" +
	"\x12ServiceTargetState\x12A\n" +
	"\aoutputs\x18\x01 \x03(\v2'.azdext.ServiceTargetState.OutputsEntryR\aoutputs\x12;\n" +
	"\tresources\x18\x02 \x03(\v2\x1d.azdext.ServiceTargetResourceR\tresources\x1a`\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.azdext.ServiceTargetOutputParameterR\x05value:\x028\x01\"l\n" +
	"\x1bServiceTargetInputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\tR\fdefaultValue\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"H\n" +
	"\x1cServiceTargetOutputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\x15ServiceTargetResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18ServiceTargetNameRequest\"/\n" +
	"\x19ServiceTargetNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"{\n" +
	"\x1eServiceTargetInitializeRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x126\n" +
	"\aoptions\x18\x02 \x01(\v2\x1c.azdext.ServiceTargetOptionsR\aoptions\"!\n" +
	"\x1fServiceTargetInitializeResponse\"X\n" +
	"\x19ServiceTargetStateRequest\x12;\n" +
	"\aoptions\x18\x01 \x01(\v2!.azdext.ServiceTargetStateOptionsR\aoptions\"a\n" +
	"\x1aServiceTargetStateResponse\x12C\n" +
	"\fstate_result\x18\x01 \x01(\v2 .azdext.ServiceTargetStateResultR\vstateResult\"\xed\x02\n" +
	"\x14ServiceTargetOptions\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12_\n" +
	"\x11deployment_stacks\x18\x04 \x03(\v22.azdext.ServiceTargetOptions.DeploymentStacksEntryR\x10deploymentStacks\x126\n" +
	"\x17ignore_deployment_state\x18\x05 \x01(\bR\x15ignoreDeploymentState\x12/\n" +
	"\x06config\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06config\x1aC\n" +
	"\x15DeploymentStacksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x19ServiceTargetStateOptions\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\"L\n" +
	"\x18ServiceTargetStateResult\x120\n" +
	"\x05state\x18\x01 \x01(\v2\x1a.azdext.ServiceTargetStateR\x05state\"2\n" +
	"\x1cRegisterServiceTargetRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"\x1f\n" +
	"\x1dRegisterServiceTargetResponse\"O\n" +
	"\x19ServiceTargetErrorMessage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x87\x01\n" +
	"\x18GetTargetResourceRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12B\n" +
	"\x0eservice_config\x18\x02 \x01(\v2\x1b.azdext.ServiceTargetConfigR\rserviceConfig\"\\\n" +
	"\x19GetTargetResourceResponse\x12?\n" +
	"\x0ftarget_resource\x18\x01 \x01(\v2\x16.azdext.TargetResourceR\x0etargetResource\"\x95\x02\n" +
	"\x13ServiceTargetConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12Q\n" +
	"\x13resource_group_name\x18\x04 \x01(\v2!.azdext.ResourceGroupNameTemplateR\x11resourceGroupName\x12`\n" +
	"\x1bproject_resource_group_name\x18\x05 \x01(\v2!.azdext.ResourceGroupNameTemplateR\x18projectResourceGroupName\"R\n" +
	"\x19ResourceGroupNameTemplate\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x19\n" +
	"\bis_empty\x18\x02 \x01(\bR\aisEmpty\"\xb3\x01\n" +
	"\x0eTargetResource\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12.\n" +
	"\x13resource_group_name\x18\x02 \x01(\tR\x11resourceGroupName\x12#\n" +
	"\rresource_name\x18\x03 \x01(\tR\fresourceName\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\"\xee\x01\n" +
	"\x1aServiceTargetDeployRequest\x12B\n" +
	"\x0eservice_config\x18\x01 \x01(\v2\x1b.azdext.ServiceTargetConfigR\rserviceConfig\x12K\n" +
	"\x0fservice_package\x18\x02 \x01(\v2\".azdext.ServiceTargetPackageResultR\x0eservicePackage\x12?\n" +
	"\x0ftarget_resource\x18\x03 \x01(\v2\x16.azdext.TargetResourceR\x0etargetResource\"e\n" +
	"\x1bServiceTargetDeployResponse\x12F\n" +
	"\rdeploy_result\x18\x01 \x01(\v2!.azdext.ServiceTargetDeployResultR\fdeployResult\"\xc6\x01\n" +
	"\x1aServiceTargetPackageResult\x12!\n" +
	"\fpackage_path\x18\x01 \x01(\tR\vpackagePath\x12I\n" +
	"\adetails\x18\x02 \x03(\v2/.azdext.ServiceTargetPackageResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x19ServiceTargetDeployResult\x12<\n" +
	"\apackage\x18\x01 \x01(\v2\".azdext.ServiceTargetPackageResultR\apackage\x12,\n" +
	"\x12target_resource_id\x18\x02 \x01(\tR\x10targetResourceId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1c\n" +
	"\tendpoints\x18\x04 \x03(\tR\tendpoints\x12\x18\n" +
	"\adetails\x18\x05 \x01(\tR\adetails\"u\n" +
	"\x1cServiceTargetProgressMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2`\n" +
	"\x14ServiceTargetService\x12H\n" +
	"\x06Stream\x12\x1c.azdext.ServiceTargetMessage\x1a\x1c.azdext.ServiceTargetMessage(\x010\x01B/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_service_target_proto_rawDescOnce sync.Once
	file_service_target_proto_rawDescData []byte
)

func file_service_target_proto_rawDescGZIP() []byte {
	file_service_target_proto_rawDescOnce.Do(func() {
		file_service_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_target_proto_rawDesc), len(file_service_target_proto_rawDesc)))
	})
	return file_service_target_proto_rawDescData
}

var file_service_target_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_service_target_proto_goTypes = []any{
	(*ServiceTargetMessage)(nil),            // 0: azdext.ServiceTargetMessage
	(*ServiceTargetState)(nil),              // 1: azdext.ServiceTargetState
	(*ServiceTargetInputParameter)(nil),     // 2: azdext.ServiceTargetInputParameter
	(*ServiceTargetOutputParameter)(nil),    // 3: azdext.ServiceTargetOutputParameter
	(*ServiceTargetResource)(nil),           // 4: azdext.ServiceTargetResource
	(*ServiceTargetNameRequest)(nil),        // 5: azdext.ServiceTargetNameRequest
	(*ServiceTargetNameResponse)(nil),       // 6: azdext.ServiceTargetNameResponse
	(*ServiceTargetInitializeRequest)(nil),  // 7: azdext.ServiceTargetInitializeRequest
	(*ServiceTargetInitializeResponse)(nil), // 8: azdext.ServiceTargetInitializeResponse
	(*ServiceTargetStateRequest)(nil),       // 9: azdext.ServiceTargetStateRequest
	(*ServiceTargetStateResponse)(nil),      // 10: azdext.ServiceTargetStateResponse
	(*ServiceTargetOptions)(nil),            // 11: azdext.ServiceTargetOptions
	(*ServiceTargetStateOptions)(nil),       // 12: azdext.ServiceTargetStateOptions
	(*ServiceTargetStateResult)(nil),        // 13: azdext.ServiceTargetStateResult
	(*RegisterServiceTargetRequest)(nil),    // 14: azdext.RegisterServiceTargetRequest
	(*RegisterServiceTargetResponse)(nil),   // 15: azdext.RegisterServiceTargetResponse
	(*ServiceTargetErrorMessage)(nil),       // 16: azdext.ServiceTargetErrorMessage
	(*GetTargetResourceRequest)(nil),        // 17: azdext.GetTargetResourceRequest
	(*GetTargetResourceResponse)(nil),       // 18: azdext.GetTargetResourceResponse
	(*ServiceTargetConfig)(nil),             // 19: azdext.ServiceTargetConfig
	(*ResourceGroupNameTemplate)(nil),       // 20: azdext.ResourceGroupNameTemplate
	(*TargetResource)(nil),                  // 21: azdext.TargetResource
	(*ServiceTargetDeployRequest)(nil),      // 22: azdext.ServiceTargetDeployRequest
	(*ServiceTargetDeployResponse)(nil),     // 23: azdext.ServiceTargetDeployResponse
	(*ServiceTargetPackageResult)(nil),      // 24: azdext.ServiceTargetPackageResult
	(*ServiceTargetDeployResult)(nil),       // 25: azdext.ServiceTargetDeployResult
	(*ServiceTargetProgressMessage)(nil),    // 26: azdext.ServiceTargetProgressMessage
	nil,                                     // 27: azdext.ServiceTargetState.OutputsEntry
	nil,                                     // 28: azdext.ServiceTargetOptions.DeploymentStacksEntry
	nil,                                     // 29: azdext.ServiceTargetPackageResult.DetailsEntry
	(*structpb.Struct)(nil),                 // 30: google.protobuf.Struct
}
var file_service_target_proto_depIdxs = []int32{
	16, // 0: azdext.ServiceTargetMessage.error:type_name -> azdext.ServiceTargetErrorMessage
	14, // 1: azdext.ServiceTargetMessage.register_service_target_request:type_name -> azdext.RegisterServiceTargetRequest
	15, // 2: azdext.ServiceTargetMessage.register_service_target_response:type_name -> azdext.RegisterServiceTargetResponse
	17, // 3: azdext.ServiceTargetMessage.get_target_resource_request:type_name -> azdext.GetTargetResourceRequest
	18, // 4: azdext.ServiceTargetMessage.get_target_resource_response:type_name -> azdext.GetTargetResourceResponse
	22, // 5: azdext.ServiceTargetMessage.deploy_request:type_name -> azdext.ServiceTargetDeployRequest
	23, // 6: azdext.ServiceTargetMessage.deploy_response:type_name -> azdext.ServiceTargetDeployResponse
	26, // 7: azdext.ServiceTargetMessage.progress_message:type_name -> azdext.ServiceTargetProgressMessage
	27, // 8: azdext.ServiceTargetState.outputs:type_name -> azdext.ServiceTargetState.OutputsEntry
	4,  // 9: azdext.ServiceTargetState.resources:type_name -> azdext.ServiceTargetResource
	11, // 10: azdext.ServiceTargetInitializeRequest.options:type_name -> azdext.ServiceTargetOptions
	12, // 11: azdext.ServiceTargetStateRequest.options:type_name -> azdext.ServiceTargetStateOptions
	13, // 12: azdext.ServiceTargetStateResponse.state_result:type_name -> azdext.ServiceTargetStateResult
	28, // 13: azdext.ServiceTargetOptions.deployment_stacks:type_name -> azdext.ServiceTargetOptions.DeploymentStacksEntry
	30, // 14: azdext.ServiceTargetOptions.config:type_name -> google.protobuf.Struct
	1,  // 15: azdext.ServiceTargetStateResult.state:type_name -> azdext.ServiceTargetState
	19, // 16: azdext.GetTargetResourceRequest.service_config:type_name -> azdext.ServiceTargetConfig
	21, // 17: azdext.GetTargetResourceResponse.target_resource:type_name -> azdext.TargetResource
	20, // 18: azdext.ServiceTargetConfig.resource_group_name:type_name -> azdext.ResourceGroupNameTemplate
	20, // 19: azdext.ServiceTargetConfig.project_resource_group_name:type_name -> azdext.ResourceGroupNameTemplate
	19, // 20: azdext.ServiceTargetDeployRequest.service_config:type_name -> azdext.ServiceTargetConfig
	24, // 21: azdext.ServiceTargetDeployRequest.service_package:type_name -> azdext.ServiceTargetPackageResult
	21, // 22: azdext.ServiceTargetDeployRequest.target_resource:type_name -> azdext.TargetResource
	25, // 23: azdext.ServiceTargetDeployResponse.deploy_result:type_name -> azdext.ServiceTargetDeployResult
	29, // 24: azdext.ServiceTargetPackageResult.details:type_name -> azdext.ServiceTargetPackageResult.DetailsEntry
	24, // 25: azdext.ServiceTargetDeployResult.package:type_name -> azdext.ServiceTargetPackageResult
	3,  // 26: azdext.ServiceTargetState.OutputsEntry.value:type_name -> azdext.ServiceTargetOutputParameter
	0,  // 27: azdext.ServiceTargetService.Stream:input_type -> azdext.ServiceTargetMessage
	0,  // 28: azdext.ServiceTargetService.Stream:output_type -> azdext.ServiceTargetMessage
	28, // [28:29] is the sub-list for method output_type
	27, // [27:28] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_service_target_proto_init() }
func file_service_target_proto_init() {
	if File_service_target_proto != nil {
		return
	}
	file_service_target_proto_msgTypes[0].OneofWrappers = []any{
		(*ServiceTargetMessage_RegisterServiceTargetRequest)(nil),
		(*ServiceTargetMessage_RegisterServiceTargetResponse)(nil),
		(*ServiceTargetMessage_GetTargetResourceRequest)(nil),
		(*ServiceTargetMessage_GetTargetResourceResponse)(nil),
		(*ServiceTargetMessage_DeployRequest)(nil),
		(*ServiceTargetMessage_DeployResponse)(nil),
		(*ServiceTargetMessage_ProgressMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_target_proto_rawDesc), len(file_service_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_target_proto_goTypes,
		DependencyIndexes: file_service_target_proto_depIdxs,
		MessageInfos:      file_service_target_proto_msgTypes,
	}.Build()
	File_service_target_proto = out.File
	file_service_target_proto_goTypes = nil
	file_service_target_proto_depIdxs = nil
}
