// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: service_target.proto

package azdext

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope for all possible service target messages (requests and responses)
type ServiceTargetMessage struct {
	state     protoimpl.MessageState     `protogen:"open.v1"`
	RequestId string                     `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error     *ServiceTargetErrorMessage `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*ServiceTargetMessage_RegisterProviderRequest
	//	*ServiceTargetMessage_RegisterProviderResponse
	//	*ServiceTargetMessage_NameRequest
	//	*ServiceTargetMessage_NameResponse
	//	*ServiceTargetMessage_InitializeRequest
	//	*ServiceTargetMessage_InitializeResponse
	//	*ServiceTargetMessage_StateRequest
	//	*ServiceTargetMessage_StateResponse
	MessageType   isServiceTargetMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetMessage) Reset() {
	*x = ServiceTargetMessage{}
	mi := &file_service_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetMessage) ProtoMessage() {}

func (x *ServiceTargetMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetMessage.ProtoReflect.Descriptor instead.
func (*ServiceTargetMessage) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceTargetMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceTargetMessage) GetError() *ServiceTargetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ServiceTargetMessage) GetMessageType() isServiceTargetMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *ServiceTargetMessage) GetRegisterProviderRequest() *ServiceTargetRegisterProviderRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_RegisterProviderRequest); ok {
			return x.RegisterProviderRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetRegisterProviderResponse() *ServiceTargetRegisterProviderResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_RegisterProviderResponse); ok {
			return x.RegisterProviderResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetNameRequest() *ServiceTargetNameRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_NameRequest); ok {
			return x.NameRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetNameResponse() *ServiceTargetNameResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_NameResponse); ok {
			return x.NameResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetInitializeRequest() *ServiceTargetInitializeRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_InitializeRequest); ok {
			return x.InitializeRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetInitializeResponse() *ServiceTargetInitializeResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_InitializeResponse); ok {
			return x.InitializeResponse
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetStateRequest() *ServiceTargetStateRequest {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_StateRequest); ok {
			return x.StateRequest
		}
	}
	return nil
}

func (x *ServiceTargetMessage) GetStateResponse() *ServiceTargetStateResponse {
	if x != nil {
		if x, ok := x.MessageType.(*ServiceTargetMessage_StateResponse); ok {
			return x.StateResponse
		}
	}
	return nil
}

type isServiceTargetMessage_MessageType interface {
	isServiceTargetMessage_MessageType()
}

type ServiceTargetMessage_RegisterProviderRequest struct {
	RegisterProviderRequest *ServiceTargetRegisterProviderRequest `protobuf:"bytes,2,opt,name=register_provider_request,json=registerProviderRequest,proto3,oneof"`
}

type ServiceTargetMessage_RegisterProviderResponse struct {
	RegisterProviderResponse *ServiceTargetRegisterProviderResponse `protobuf:"bytes,3,opt,name=register_provider_response,json=registerProviderResponse,proto3,oneof"`
}

type ServiceTargetMessage_NameRequest struct {
	NameRequest *ServiceTargetNameRequest `protobuf:"bytes,4,opt,name=name_request,json=nameRequest,proto3,oneof"`
}

type ServiceTargetMessage_NameResponse struct {
	NameResponse *ServiceTargetNameResponse `protobuf:"bytes,5,opt,name=name_response,json=nameResponse,proto3,oneof"`
}

type ServiceTargetMessage_InitializeRequest struct {
	InitializeRequest *ServiceTargetInitializeRequest `protobuf:"bytes,6,opt,name=initialize_request,json=initializeRequest,proto3,oneof"`
}

type ServiceTargetMessage_InitializeResponse struct {
	InitializeResponse *ServiceTargetInitializeResponse `protobuf:"bytes,7,opt,name=initialize_response,json=initializeResponse,proto3,oneof"`
}

type ServiceTargetMessage_StateRequest struct {
	StateRequest *ServiceTargetStateRequest `protobuf:"bytes,8,opt,name=state_request,json=stateRequest,proto3,oneof"`
}

type ServiceTargetMessage_StateResponse struct {
	StateResponse *ServiceTargetStateResponse `protobuf:"bytes,9,opt,name=state_response,json=stateResponse,proto3,oneof"`
}

func (*ServiceTargetMessage_RegisterProviderRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_RegisterProviderResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_NameRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_NameResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_InitializeRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_InitializeResponse) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_StateRequest) isServiceTargetMessage_MessageType() {}

func (*ServiceTargetMessage_StateResponse) isServiceTargetMessage_MessageType() {}

// State
type ServiceTargetState struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Outputs       map[string]*ServiceTargetOutputParameter `protobuf:"bytes,1,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     []*ServiceTargetResource                 `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetState) Reset() {
	*x = ServiceTargetState{}
	mi := &file_service_target_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetState) ProtoMessage() {}

func (x *ServiceTargetState) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetState.ProtoReflect.Descriptor instead.
func (*ServiceTargetState) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceTargetState) GetOutputs() map[string]*ServiceTargetOutputParameter {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ServiceTargetState) GetResources() []*ServiceTargetResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

// InputParameter
type ServiceTargetInputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInputParameter) Reset() {
	*x = ServiceTargetInputParameter{}
	mi := &file_service_target_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInputParameter) ProtoMessage() {}

func (x *ServiceTargetInputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInputParameter.ProtoReflect.Descriptor instead.
func (*ServiceTargetInputParameter) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceTargetInputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceTargetInputParameter) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ServiceTargetInputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OutputParameter
type ServiceTargetOutputParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetOutputParameter) Reset() {
	*x = ServiceTargetOutputParameter{}
	mi := &file_service_target_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetOutputParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetOutputParameter) ProtoMessage() {}

func (x *ServiceTargetOutputParameter) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetOutputParameter.ProtoReflect.Descriptor instead.
func (*ServiceTargetOutputParameter) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceTargetOutputParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceTargetOutputParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Resource
type ServiceTargetResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetResource) Reset() {
	*x = ServiceTargetResource{}
	mi := &file_service_target_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetResource) ProtoMessage() {}

func (x *ServiceTargetResource) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetResource.ProtoReflect.Descriptor instead.
func (*ServiceTargetResource) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceTargetResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ServiceTargetNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetNameRequest) Reset() {
	*x = ServiceTargetNameRequest{}
	mi := &file_service_target_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetNameRequest) ProtoMessage() {}

func (x *ServiceTargetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetNameRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetNameRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{5}
}

type ServiceTargetNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetNameResponse) Reset() {
	*x = ServiceTargetNameResponse{}
	mi := &file_service_target_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetNameResponse) ProtoMessage() {}

func (x *ServiceTargetNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetNameResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetNameResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceTargetNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServiceTargetInitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	Options       *ServiceTargetOptions  `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInitializeRequest) Reset() {
	*x = ServiceTargetInitializeRequest{}
	mi := &file_service_target_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInitializeRequest) ProtoMessage() {}

func (x *ServiceTargetInitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInitializeRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetInitializeRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceTargetInitializeRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *ServiceTargetInitializeRequest) GetOptions() *ServiceTargetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ServiceTargetInitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetInitializeResponse) Reset() {
	*x = ServiceTargetInitializeResponse{}
	mi := &file_service_target_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetInitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetInitializeResponse) ProtoMessage() {}

func (x *ServiceTargetInitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetInitializeResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetInitializeResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{8}
}

type ServiceTargetStateRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Options       *ServiceTargetStateOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateRequest) Reset() {
	*x = ServiceTargetStateRequest{}
	mi := &file_service_target_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateRequest) ProtoMessage() {}

func (x *ServiceTargetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceTargetStateRequest) GetOptions() *ServiceTargetStateOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type ServiceTargetStateResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	StateResult   *ServiceTargetStateResult `protobuf:"bytes,1,opt,name=state_result,json=stateResult,proto3" json:"state_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateResponse) Reset() {
	*x = ServiceTargetStateResponse{}
	mi := &file_service_target_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateResponse) ProtoMessage() {}

func (x *ServiceTargetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceTargetStateResponse) GetStateResult() *ServiceTargetStateResult {
	if x != nil {
		return x.StateResult
	}
	return nil
}

// Core options and result wrappers
type ServiceTargetOptions struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Provider              string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Path                  string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Module                string                 `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	DeploymentStacks      map[string]string      `protobuf:"bytes,4,rep,name=deployment_stacks,json=deploymentStacks,proto3" json:"deployment_stacks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IgnoreDeploymentState bool                   `protobuf:"varint,5,opt,name=ignore_deployment_state,json=ignoreDeploymentState,proto3" json:"ignore_deployment_state,omitempty"`
	Config                *structpb.Struct       `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServiceTargetOptions) Reset() {
	*x = ServiceTargetOptions{}
	mi := &file_service_target_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetOptions) ProtoMessage() {}

func (x *ServiceTargetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetOptions.ProtoReflect.Descriptor instead.
func (*ServiceTargetOptions) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceTargetOptions) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ServiceTargetOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServiceTargetOptions) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ServiceTargetOptions) GetDeploymentStacks() map[string]string {
	if x != nil {
		return x.DeploymentStacks
	}
	return nil
}

func (x *ServiceTargetOptions) GetIgnoreDeploymentState() bool {
	if x != nil {
		return x.IgnoreDeploymentState
	}
	return false
}

func (x *ServiceTargetOptions) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ServiceTargetStateOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Add fields as needed
	Hint          string `protobuf:"bytes,1,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateOptions) Reset() {
	*x = ServiceTargetStateOptions{}
	mi := &file_service_target_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateOptions) ProtoMessage() {}

func (x *ServiceTargetStateOptions) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateOptions.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateOptions) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{12}
}

func (x *ServiceTargetStateOptions) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type ServiceTargetStateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *ServiceTargetState    `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetStateResult) Reset() {
	*x = ServiceTargetStateResult{}
	mi := &file_service_target_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetStateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetStateResult) ProtoMessage() {}

func (x *ServiceTargetStateResult) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetStateResult.ProtoReflect.Descriptor instead.
func (*ServiceTargetStateResult) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceTargetStateResult) GetState() *ServiceTargetState {
	if x != nil {
		return x.State
	}
	return nil
}

type ServiceTargetRegisterProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // unique identifier for the provider
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetRegisterProviderRequest) Reset() {
	*x = ServiceTargetRegisterProviderRequest{}
	mi := &file_service_target_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetRegisterProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetRegisterProviderRequest) ProtoMessage() {}

func (x *ServiceTargetRegisterProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetRegisterProviderRequest.ProtoReflect.Descriptor instead.
func (*ServiceTargetRegisterProviderRequest) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{14}
}

func (x *ServiceTargetRegisterProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceTargetRegisterProviderRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ServiceTargetRegisterProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetRegisterProviderResponse) Reset() {
	*x = ServiceTargetRegisterProviderResponse{}
	mi := &file_service_target_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetRegisterProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetRegisterProviderResponse) ProtoMessage() {}

func (x *ServiceTargetRegisterProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetRegisterProviderResponse.ProtoReflect.Descriptor instead.
func (*ServiceTargetRegisterProviderResponse) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{15}
}

type ServiceTargetErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceTargetErrorMessage) Reset() {
	*x = ServiceTargetErrorMessage{}
	mi := &file_service_target_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceTargetErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceTargetErrorMessage) ProtoMessage() {}

func (x *ServiceTargetErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_service_target_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceTargetErrorMessage.ProtoReflect.Descriptor instead.
func (*ServiceTargetErrorMessage) Descriptor() ([]byte, []int) {
	return file_service_target_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceTargetErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServiceTargetErrorMessage) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_service_target_proto protoreflect.FileDescriptor

const file_service_target_proto_rawDesc = "" +
	"\n" +
	"\x14service_target.proto\x12\x06azdext\x1a$include/google/protobuf/struct.proto\"\xb6\x06\n" +
	"\x14ServiceTargetMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x127\n" +
	"\x05error\x18c \x01(\v2!.azdext.ServiceTargetErrorMessageR\x05error\x12j\n" +
	"\x19register_provider_request\x18\x02 \x01(\v2,.azdext.ServiceTargetRegisterProviderRequestH\x00R\x17registerProviderRequest\x12m\n" +
	"\x1aregister_provider_response\x18\x03 \x01(\v2-.azdext.ServiceTargetRegisterProviderResponseH\x00R\x18registerProviderResponse\x12E\n" +
	"\fname_request\x18\x04 \x01(\v2 .azdext.ServiceTargetNameRequestH\x00R\vnameRequest\x12H\n" +
	"\rname_response\x18\x05 \x01(\v2!.azdext.ServiceTargetNameResponseH\x00R\fnameResponse\x12W\n" +
	"\x12initialize_request\x18\x06 \x01(\v2&.azdext.ServiceTargetInitializeRequestH\x00R\x11initializeRequest\x12Z\n" +
	"\x13initialize_response\x18\a \x01(\v2'.azdext.ServiceTargetInitializeResponseH\x00R\x12initializeResponse\x12H\n" +
	"\rstate_request\x18\b \x01(\v2!.azdext.ServiceTargetStateRequestH\x00R\fstateRequest\x12K\n" +
	"\x0estate_response\x18\t \x01(\v2\".azdext.ServiceTargetStateResponseH\x00R\rstateResponseB\x0e\n" +
	"\fmessage_type\"\xf6\x01\n" +
	"\x12ServiceTargetState\x12A\n" +
	"\aoutputs\x18\x01 \x03(\v2'.azdext.ServiceTargetState.OutputsEntryR\aoutputs\x12;\n" +
	"\tresources\x18\x02 \x03(\v2\x1d.azdext.ServiceTargetResourceR\tresources\x1a`\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.azdext.ServiceTargetOutputParameterR\x05value:\x028\x01\"l\n" +
	"\x1bServiceTargetInputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rdefault_value\x18\x02 \x01(\tR\fdefaultValue\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"H\n" +
	"\x1cServiceTargetOutputParameter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"'\n" +
	"\x15ServiceTargetResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x18ServiceTargetNameRequest\"/\n" +
	"\x19ServiceTargetNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"{\n" +
	"\x1eServiceTargetInitializeRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x126\n" +
	"\aoptions\x18\x02 \x01(\v2\x1c.azdext.ServiceTargetOptionsR\aoptions\"!\n" +
	"\x1fServiceTargetInitializeResponse\"X\n" +
	"\x19ServiceTargetStateRequest\x12;\n" +
	"\aoptions\x18\x01 \x01(\v2!.azdext.ServiceTargetStateOptionsR\aoptions\"a\n" +
	"\x1aServiceTargetStateResponse\x12C\n" +
	"\fstate_result\x18\x01 \x01(\v2 .azdext.ServiceTargetStateResultR\vstateResult\"\xed\x02\n" +
	"\x14ServiceTargetOptions\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06module\x18\x03 \x01(\tR\x06module\x12_\n" +
	"\x11deployment_stacks\x18\x04 \x03(\v22.azdext.ServiceTargetOptions.DeploymentStacksEntryR\x10deploymentStacks\x126\n" +
	"\x17ignore_deployment_state\x18\x05 \x01(\bR\x15ignoreDeploymentState\x12/\n" +
	"\x06config\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06config\x1aC\n" +
	"\x15DeploymentStacksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x19ServiceTargetStateOptions\x12\x12\n" +
	"\x04hint\x18\x01 \x01(\tR\x04hint\"L\n" +
	"\x18ServiceTargetStateResult\x120\n" +
	"\x05state\x18\x01 \x01(\v2\x1a.azdext.ServiceTargetStateR\x05state\"]\n" +
	"$ServiceTargetRegisterProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"'\n" +
	"%ServiceTargetRegisterProviderResponse\"O\n" +
	"\x19ServiceTargetErrorMessage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails2`\n" +
	"\x14ServiceTargetService\x12H\n" +
	"\x06Stream\x12\x1c.azdext.ServiceTargetMessage\x1a\x1c.azdext.ServiceTargetMessage(\x010\x01B/Z-github.com/azure/azure-dev/cli/azd/pkg/azdextb\x06proto3"

var (
	file_service_target_proto_rawDescOnce sync.Once
	file_service_target_proto_rawDescData []byte
)

func file_service_target_proto_rawDescGZIP() []byte {
	file_service_target_proto_rawDescOnce.Do(func() {
		file_service_target_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_target_proto_rawDesc), len(file_service_target_proto_rawDesc)))
	})
	return file_service_target_proto_rawDescData
}

var file_service_target_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_service_target_proto_goTypes = []any{
	(*ServiceTargetMessage)(nil),                  // 0: azdext.ServiceTargetMessage
	(*ServiceTargetState)(nil),                    // 1: azdext.ServiceTargetState
	(*ServiceTargetInputParameter)(nil),           // 2: azdext.ServiceTargetInputParameter
	(*ServiceTargetOutputParameter)(nil),          // 3: azdext.ServiceTargetOutputParameter
	(*ServiceTargetResource)(nil),                 // 4: azdext.ServiceTargetResource
	(*ServiceTargetNameRequest)(nil),              // 5: azdext.ServiceTargetNameRequest
	(*ServiceTargetNameResponse)(nil),             // 6: azdext.ServiceTargetNameResponse
	(*ServiceTargetInitializeRequest)(nil),        // 7: azdext.ServiceTargetInitializeRequest
	(*ServiceTargetInitializeResponse)(nil),       // 8: azdext.ServiceTargetInitializeResponse
	(*ServiceTargetStateRequest)(nil),             // 9: azdext.ServiceTargetStateRequest
	(*ServiceTargetStateResponse)(nil),            // 10: azdext.ServiceTargetStateResponse
	(*ServiceTargetOptions)(nil),                  // 11: azdext.ServiceTargetOptions
	(*ServiceTargetStateOptions)(nil),             // 12: azdext.ServiceTargetStateOptions
	(*ServiceTargetStateResult)(nil),              // 13: azdext.ServiceTargetStateResult
	(*ServiceTargetRegisterProviderRequest)(nil),  // 14: azdext.ServiceTargetRegisterProviderRequest
	(*ServiceTargetRegisterProviderResponse)(nil), // 15: azdext.ServiceTargetRegisterProviderResponse
	(*ServiceTargetErrorMessage)(nil),             // 16: azdext.ServiceTargetErrorMessage
	nil,                                           // 17: azdext.ServiceTargetState.OutputsEntry
	nil,                                           // 18: azdext.ServiceTargetOptions.DeploymentStacksEntry
	(*structpb.Struct)(nil),                       // 19: google.protobuf.Struct
}
var file_service_target_proto_depIdxs = []int32{
	16, // 0: azdext.ServiceTargetMessage.error:type_name -> azdext.ServiceTargetErrorMessage
	14, // 1: azdext.ServiceTargetMessage.register_provider_request:type_name -> azdext.ServiceTargetRegisterProviderRequest
	15, // 2: azdext.ServiceTargetMessage.register_provider_response:type_name -> azdext.ServiceTargetRegisterProviderResponse
	5,  // 3: azdext.ServiceTargetMessage.name_request:type_name -> azdext.ServiceTargetNameRequest
	6,  // 4: azdext.ServiceTargetMessage.name_response:type_name -> azdext.ServiceTargetNameResponse
	7,  // 5: azdext.ServiceTargetMessage.initialize_request:type_name -> azdext.ServiceTargetInitializeRequest
	8,  // 6: azdext.ServiceTargetMessage.initialize_response:type_name -> azdext.ServiceTargetInitializeResponse
	9,  // 7: azdext.ServiceTargetMessage.state_request:type_name -> azdext.ServiceTargetStateRequest
	10, // 8: azdext.ServiceTargetMessage.state_response:type_name -> azdext.ServiceTargetStateResponse
	17, // 9: azdext.ServiceTargetState.outputs:type_name -> azdext.ServiceTargetState.OutputsEntry
	4,  // 10: azdext.ServiceTargetState.resources:type_name -> azdext.ServiceTargetResource
	11, // 11: azdext.ServiceTargetInitializeRequest.options:type_name -> azdext.ServiceTargetOptions
	12, // 12: azdext.ServiceTargetStateRequest.options:type_name -> azdext.ServiceTargetStateOptions
	13, // 13: azdext.ServiceTargetStateResponse.state_result:type_name -> azdext.ServiceTargetStateResult
	18, // 14: azdext.ServiceTargetOptions.deployment_stacks:type_name -> azdext.ServiceTargetOptions.DeploymentStacksEntry
	19, // 15: azdext.ServiceTargetOptions.config:type_name -> google.protobuf.Struct
	1,  // 16: azdext.ServiceTargetStateResult.state:type_name -> azdext.ServiceTargetState
	3,  // 17: azdext.ServiceTargetState.OutputsEntry.value:type_name -> azdext.ServiceTargetOutputParameter
	0,  // 18: azdext.ServiceTargetService.Stream:input_type -> azdext.ServiceTargetMessage
	0,  // 19: azdext.ServiceTargetService.Stream:output_type -> azdext.ServiceTargetMessage
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_service_target_proto_init() }
func file_service_target_proto_init() {
	if File_service_target_proto != nil {
		return
	}
	file_service_target_proto_msgTypes[0].OneofWrappers = []any{
		(*ServiceTargetMessage_RegisterProviderRequest)(nil),
		(*ServiceTargetMessage_RegisterProviderResponse)(nil),
		(*ServiceTargetMessage_NameRequest)(nil),
		(*ServiceTargetMessage_NameResponse)(nil),
		(*ServiceTargetMessage_InitializeRequest)(nil),
		(*ServiceTargetMessage_InitializeResponse)(nil),
		(*ServiceTargetMessage_StateRequest)(nil),
		(*ServiceTargetMessage_StateResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_target_proto_rawDesc), len(file_service_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_target_proto_goTypes,
		DependencyIndexes: file_service_target_proto_depIdxs,
		MessageInfos:      file_service_target_proto_msgTypes,
	}.Build()
	File_service_target_proto = out.File
	file_service_target_proto_goTypes = nil
	file_service_target_proto_depIdxs = nil
}
